// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.protobuf.nano;

@SuppressWarnings("hiding")
public final class FloatValue extends
    com.google.protobuf.nano.MessageNano {

  private static volatile FloatValue[] _emptyArray;
  public static FloatValue[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new FloatValue[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional float value = 1;
  public float value;

  public FloatValue() {
    clear();
  }

  public FloatValue clear() {
    value = 0F;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (java.lang.Float.floatToIntBits(this.value)
        != java.lang.Float.floatToIntBits(0F)) {
      output.writeFloat(1, this.value);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (java.lang.Float.floatToIntBits(this.value)
        != java.lang.Float.floatToIntBits(0F)) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeFloatSize(1, this.value);
    }
    return size;
  }

  @Override
  public FloatValue mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 13: {
          this.value = input.readFloat();
          break;
        }
      }
    }
  }

  public static FloatValue parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new FloatValue(), data);
  }

  public static FloatValue parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new FloatValue().mergeFrom(input);
  }
}
