// Generated by the protocol buffer compiler.  DO NOT EDIT!

package maple.proto.nano;

@SuppressWarnings("hiding")
public interface Eventlog {

  public static final class EventLogGetLogEntriesResponse extends
      com.google.protobuf.nano.MessageNano {

    // enum ErrorType
    @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.SOURCE)
    @android.support.annotation.IntDef({
      NONE,
      UNKNOWN_ERROR,
      FORBIDDEN,
      BAD_REQUEST,
    })
    public @interface ErrorType {
    }

    public static final int NONE = 0;
    public static final int UNKNOWN_ERROR = 1;
    public static final int FORBIDDEN = 2;
    public static final int BAD_REQUEST = 3;

    private static volatile EventLogGetLogEntriesResponse[] _emptyArray;
    public static EventLogGetLogEntriesResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new EventLogGetLogEntriesResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .proto.EventLogGetLogEntriesResponse.ErrorType error = 1;
    @maple.proto.nano.Eventlog.EventLogGetLogEntriesResponse.ErrorType
    public int error;

    // repeated .proto.LogEntry log_entries = 2;
    public maple.proto.nano.Eventlog.LogEntry[] logEntries;

    public EventLogGetLogEntriesResponse() {
      clear();
    }

    public EventLogGetLogEntriesResponse clear() {
      error = maple.proto.nano.Eventlog.EventLogGetLogEntriesResponse.NONE;
      logEntries = maple.proto.nano.Eventlog.LogEntry.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.error != maple.proto.nano.Eventlog.EventLogGetLogEntriesResponse.NONE) {
        output.writeInt32(1, this.error);
      }
      if (this.logEntries != null && this.logEntries.length > 0) {
        for (int i = 0; i < this.logEntries.length; i++) {
          maple.proto.nano.Eventlog.LogEntry element = this.logEntries[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.error != maple.proto.nano.Eventlog.EventLogGetLogEntriesResponse.NONE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.error);
      }
      if (this.logEntries != null && this.logEntries.length > 0) {
        for (int i = 0; i < this.logEntries.length; i++) {
          maple.proto.nano.Eventlog.LogEntry element = this.logEntries[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      return size;
    }

    @Override
    public EventLogGetLogEntriesResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case maple.proto.nano.Eventlog.EventLogGetLogEntriesResponse.NONE:
              case maple.proto.nano.Eventlog.EventLogGetLogEntriesResponse.UNKNOWN_ERROR:
              case maple.proto.nano.Eventlog.EventLogGetLogEntriesResponse.FORBIDDEN:
              case maple.proto.nano.Eventlog.EventLogGetLogEntriesResponse.BAD_REQUEST:
                this.error = value;
                break;
            }
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.logEntries == null ? 0 : this.logEntries.length;
            maple.proto.nano.Eventlog.LogEntry[] newArray =
                new maple.proto.nano.Eventlog.LogEntry[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.logEntries, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new maple.proto.nano.Eventlog.LogEntry();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new maple.proto.nano.Eventlog.LogEntry();
            input.readMessage(newArray[i]);
            this.logEntries = newArray;
            break;
          }
        }
      }
    }

    public static EventLogGetLogEntriesResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new EventLogGetLogEntriesResponse(), data);
    }

    public static EventLogGetLogEntriesResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new EventLogGetLogEntriesResponse().mergeFrom(input);
    }
  }

  public static final class LogEntryEvent extends
      com.google.protobuf.nano.MessageNano {

    private static volatile LogEntryEvent[] _emptyArray;
    public static LogEntryEvent[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LogEntryEvent[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 timestamp = 1;
    public long timestamp;

    // optional string channel_id = 2;
    public java.lang.String channelId;

    // optional string community_id = 3;
    public java.lang.String communityId;

    // optional string source_user_id = 4;
    public java.lang.String sourceUserId;

    // optional string target_id = 5;
    public java.lang.String targetId;

    // optional .proto.WebsocketMessage target_message = 6;
    public maple.proto.nano.Message.WebsocketMessage targetMessage;

    // optional .proto.LogEntry.TargetType target_type = 7;
    @maple.proto.nano.Eventlog.LogEntry.TargetType
    public int targetType;

    // optional string action = 8;
    public java.lang.String action;

    // optional .proto.LogEntry.ActionType action_type = 9;
    @maple.proto.nano.Eventlog.LogEntry.ActionType
    public int actionType;

    // optional string reason = 10;
    public java.lang.String reason;

    // optional string description = 11;
    public java.lang.String description;

    public LogEntryEvent() {
      clear();
    }

    public LogEntryEvent clear() {
      timestamp = 0L;
      channelId = "";
      communityId = "";
      sourceUserId = "";
      targetId = "";
      targetMessage = null;
      targetType = maple.proto.nano.Eventlog.LogEntry.NOTARGET;
      action = "";
      actionType = maple.proto.nano.Eventlog.LogEntry.OTHER;
      reason = "";
      description = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.timestamp != 0L) {
        output.writeInt64(1, this.timestamp);
      }
      if (!this.channelId.equals("")) {
        output.writeString(2, this.channelId);
      }
      if (!this.communityId.equals("")) {
        output.writeString(3, this.communityId);
      }
      if (!this.sourceUserId.equals("")) {
        output.writeString(4, this.sourceUserId);
      }
      if (!this.targetId.equals("")) {
        output.writeString(5, this.targetId);
      }
      if (this.targetMessage != null) {
        output.writeMessage(6, this.targetMessage);
      }
      if (this.targetType != maple.proto.nano.Eventlog.LogEntry.NOTARGET) {
        output.writeInt32(7, this.targetType);
      }
      if (!this.action.equals("")) {
        output.writeString(8, this.action);
      }
      if (this.actionType != maple.proto.nano.Eventlog.LogEntry.OTHER) {
        output.writeInt32(9, this.actionType);
      }
      if (!this.reason.equals("")) {
        output.writeString(10, this.reason);
      }
      if (!this.description.equals("")) {
        output.writeString(11, this.description);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.timestamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.timestamp);
      }
      if (!this.channelId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.channelId);
      }
      if (!this.communityId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.communityId);
      }
      if (!this.sourceUserId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.sourceUserId);
      }
      if (!this.targetId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.targetId);
      }
      if (this.targetMessage != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6, this.targetMessage);
      }
      if (this.targetType != maple.proto.nano.Eventlog.LogEntry.NOTARGET) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(7, this.targetType);
      }
      if (!this.action.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.action);
      }
      if (this.actionType != maple.proto.nano.Eventlog.LogEntry.OTHER) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(9, this.actionType);
      }
      if (!this.reason.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.reason);
      }
      if (!this.description.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.description);
      }
      return size;
    }

    @Override
    public LogEntryEvent mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.timestamp = input.readInt64();
            break;
          }
          case 18: {
            this.channelId = input.readString();
            break;
          }
          case 26: {
            this.communityId = input.readString();
            break;
          }
          case 34: {
            this.sourceUserId = input.readString();
            break;
          }
          case 42: {
            this.targetId = input.readString();
            break;
          }
          case 50: {
            if (this.targetMessage == null) {
              this.targetMessage = new maple.proto.nano.Message.WebsocketMessage();
            }
            input.readMessage(this.targetMessage);
            break;
          }
          case 56: {
            int value = input.readInt32();
            switch (value) {
              case maple.proto.nano.Eventlog.LogEntry.NOTARGET:
              case maple.proto.nano.Eventlog.LogEntry.USER:
              case maple.proto.nano.Eventlog.LogEntry.MESSAGE:
                this.targetType = value;
                break;
            }
            break;
          }
          case 66: {
            this.action = input.readString();
            break;
          }
          case 72: {
            int value = input.readInt32();
            switch (value) {
              case maple.proto.nano.Eventlog.LogEntry.OTHER:
              case maple.proto.nano.Eventlog.LogEntry.KICK_BAN:
              case maple.proto.nano.Eventlog.LogEntry.MESSAGE_DELETE:
              case maple.proto.nano.Eventlog.LogEntry.MESSAGE_PURGE:
                this.actionType = value;
                break;
            }
            break;
          }
          case 82: {
            this.reason = input.readString();
            break;
          }
          case 90: {
            this.description = input.readString();
            break;
          }
        }
      }
    }

    public static LogEntryEvent parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LogEntryEvent(), data);
    }

    public static LogEntryEvent parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LogEntryEvent().mergeFrom(input);
    }
  }

  public static final class LogEntry extends
      com.google.protobuf.nano.MessageNano {

    // enum TargetType
    @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.SOURCE)
    @android.support.annotation.IntDef({
      NOTARGET,
      USER,
      MESSAGE,
    })
    public @interface TargetType {
    }

    public static final int NOTARGET = 0;
    public static final int USER = 1;
    public static final int MESSAGE = 2;

    // enum ActionType
    @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.SOURCE)
    @android.support.annotation.IntDef({
      OTHER,
      KICK_BAN,
      MESSAGE_DELETE,
      MESSAGE_PURGE,
    })
    public @interface ActionType {
    }

    public static final int OTHER = 0;
    public static final int KICK_BAN = 1;
    public static final int MESSAGE_DELETE = 2;
    public static final int MESSAGE_PURGE = 3;
    public static final int TARGET_USER_FIELD_NUMBER = 6;
    public static final int TARGET_MESSAGE_FIELD_NUMBER = 7;
    private int targetCase_ = 0;
    private java.lang.Object target_;
    public int getTargetCase() {
      return this.targetCase_;
    }
    public LogEntry clearTarget() {
      this.targetCase_ = 0;
      this.target_ = null;
      return this;
    }

    private static volatile LogEntry[] _emptyArray;
    public static LogEntry[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LogEntry[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string id = 1;
    public java.lang.String id;

    // optional int64 timestamp = 2;
    public long timestamp;

    // optional string channel_id = 3;
    public java.lang.String channelId;

    // optional string community_id = 4;
    public java.lang.String communityId;

    // optional .proto.ChatUser source_user = 5;
    public maple.proto.nano.Profile.ChatUser sourceUser;

    // optional .proto.ChatUser target_user = 6;
    public boolean hasTargetUser() {
      return this.targetCase_ == 6;
    }
    public maple.proto.nano.Profile.ChatUser getTargetUser() {
      if (this.targetCase_ == 6) {
        return (maple.proto.nano.Profile.ChatUser) this.target_;
      }
      return null;
    }
    public LogEntry setTargetUser(maple.proto.nano.Profile.ChatUser value) {
      if (value == null) { throw new java.lang.NullPointerException(); }
      this.targetCase_ = 6;
      this.target_ = value;
      return this;
    }

    // optional .proto.WebsocketMessage target_message = 7;
    public boolean hasTargetMessage() {
      return this.targetCase_ == 7;
    }
    public maple.proto.nano.Message.WebsocketMessage getTargetMessage() {
      if (this.targetCase_ == 7) {
        return (maple.proto.nano.Message.WebsocketMessage) this.target_;
      }
      return null;
    }
    public LogEntry setTargetMessage(maple.proto.nano.Message.WebsocketMessage value) {
      if (value == null) { throw new java.lang.NullPointerException(); }
      this.targetCase_ = 7;
      this.target_ = value;
      return this;
    }

    // optional .proto.LogEntry.TargetType target_type = 8;
    @maple.proto.nano.Eventlog.LogEntry.TargetType
    public int targetType;

    // optional string action = 9;
    public java.lang.String action;

    // optional .proto.LogEntry.ActionType action_type = 10;
    @maple.proto.nano.Eventlog.LogEntry.ActionType
    public int actionType;

    // optional string reason = 11;
    public java.lang.String reason;

    // optional string description = 12;
    public java.lang.String description;

    // repeated .proto.WebsocketMessage context = 13;
    public maple.proto.nano.Message.WebsocketMessage[] context;

    public LogEntry() {
      clear();
    }

    public LogEntry clear() {
      id = "";
      timestamp = 0L;
      channelId = "";
      communityId = "";
      sourceUser = null;
      targetType = maple.proto.nano.Eventlog.LogEntry.NOTARGET;
      action = "";
      actionType = maple.proto.nano.Eventlog.LogEntry.OTHER;
      reason = "";
      description = "";
      context = maple.proto.nano.Message.WebsocketMessage.emptyArray();
      clearTarget();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.id.equals("")) {
        output.writeString(1, this.id);
      }
      if (this.timestamp != 0L) {
        output.writeInt64(2, this.timestamp);
      }
      if (!this.channelId.equals("")) {
        output.writeString(3, this.channelId);
      }
      if (!this.communityId.equals("")) {
        output.writeString(4, this.communityId);
      }
      if (this.sourceUser != null) {
        output.writeMessage(5, this.sourceUser);
      }
      if (this.targetCase_ == 6) {
        output.writeMessage(6,
            (com.google.protobuf.nano.MessageNano) this.target_);
      }
      if (this.targetCase_ == 7) {
        output.writeMessage(7,
            (com.google.protobuf.nano.MessageNano) this.target_);
      }
      if (this.targetType != maple.proto.nano.Eventlog.LogEntry.NOTARGET) {
        output.writeInt32(8, this.targetType);
      }
      if (!this.action.equals("")) {
        output.writeString(9, this.action);
      }
      if (this.actionType != maple.proto.nano.Eventlog.LogEntry.OTHER) {
        output.writeInt32(10, this.actionType);
      }
      if (!this.reason.equals("")) {
        output.writeString(11, this.reason);
      }
      if (!this.description.equals("")) {
        output.writeString(12, this.description);
      }
      if (this.context != null && this.context.length > 0) {
        for (int i = 0; i < this.context.length; i++) {
          maple.proto.nano.Message.WebsocketMessage element = this.context[i];
          if (element != null) {
            output.writeMessage(13, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.id.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.id);
      }
      if (this.timestamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.timestamp);
      }
      if (!this.channelId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.channelId);
      }
      if (!this.communityId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.communityId);
      }
      if (this.sourceUser != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5, this.sourceUser);
      }
      if (this.targetCase_ == 6) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6,
              (com.google.protobuf.nano.MessageNano) this.target_);
      }
      if (this.targetCase_ == 7) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7,
              (com.google.protobuf.nano.MessageNano) this.target_);
      }
      if (this.targetType != maple.proto.nano.Eventlog.LogEntry.NOTARGET) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(8, this.targetType);
      }
      if (!this.action.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.action);
      }
      if (this.actionType != maple.proto.nano.Eventlog.LogEntry.OTHER) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(10, this.actionType);
      }
      if (!this.reason.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.reason);
      }
      if (!this.description.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(12, this.description);
      }
      if (this.context != null && this.context.length > 0) {
        for (int i = 0; i < this.context.length; i++) {
          maple.proto.nano.Message.WebsocketMessage element = this.context[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(13, element);
          }
        }
      }
      return size;
    }

    @Override
    public LogEntry mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.id = input.readString();
            break;
          }
          case 16: {
            this.timestamp = input.readInt64();
            break;
          }
          case 26: {
            this.channelId = input.readString();
            break;
          }
          case 34: {
            this.communityId = input.readString();
            break;
          }
          case 42: {
            if (this.sourceUser == null) {
              this.sourceUser = new maple.proto.nano.Profile.ChatUser();
            }
            input.readMessage(this.sourceUser);
            break;
          }
          case 50: {
            if (!(this.targetCase_ == 6)) {
              this.target_ = new maple.proto.nano.Profile.ChatUser();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.target_);
            this.targetCase_ = 6;
            break;
          }
          case 58: {
            if (!(this.targetCase_ == 7)) {
              this.target_ = new maple.proto.nano.Message.WebsocketMessage();
            }
            input.readMessage(
                (com.google.protobuf.nano.MessageNano) this.target_);
            this.targetCase_ = 7;
            break;
          }
          case 64: {
            int value = input.readInt32();
            switch (value) {
              case maple.proto.nano.Eventlog.LogEntry.NOTARGET:
              case maple.proto.nano.Eventlog.LogEntry.USER:
              case maple.proto.nano.Eventlog.LogEntry.MESSAGE:
                this.targetType = value;
                break;
            }
            break;
          }
          case 74: {
            this.action = input.readString();
            break;
          }
          case 80: {
            int value = input.readInt32();
            switch (value) {
              case maple.proto.nano.Eventlog.LogEntry.OTHER:
              case maple.proto.nano.Eventlog.LogEntry.KICK_BAN:
              case maple.proto.nano.Eventlog.LogEntry.MESSAGE_DELETE:
              case maple.proto.nano.Eventlog.LogEntry.MESSAGE_PURGE:
                this.actionType = value;
                break;
            }
            break;
          }
          case 90: {
            this.reason = input.readString();
            break;
          }
          case 98: {
            this.description = input.readString();
            break;
          }
          case 106: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 106);
            int i = this.context == null ? 0 : this.context.length;
            maple.proto.nano.Message.WebsocketMessage[] newArray =
                new maple.proto.nano.Message.WebsocketMessage[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.context, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new maple.proto.nano.Message.WebsocketMessage();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new maple.proto.nano.Message.WebsocketMessage();
            input.readMessage(newArray[i]);
            this.context = newArray;
            break;
          }
        }
      }
    }

    public static LogEntry parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LogEntry(), data);
    }

    public static LogEntry parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LogEntry().mergeFrom(input);
    }
  }
}
