// Generated by the protocol buffer compiler.  DO NOT EDIT!

package maple.proto.nano;

@SuppressWarnings("hiding")
public interface Userlist {

  public static final class RPCUserlistGetChannelUsersRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RPCUserlistGetChannelUsersRequest[] _emptyArray;
    public static RPCUserlistGetChannelUsersRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RPCUserlistGetChannelUsersRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string requesting_user_id = 1;
    public java.lang.String requestingUserId;

    // optional string channel_id = 2;
    public java.lang.String channelId;

    // optional int64 size = 3;
    public long size;

    // optional int64 from = 4;
    public long from;

    // optional bool exclude_offline = 5;
    public boolean excludeOffline;

    public RPCUserlistGetChannelUsersRequest() {
      clear();
    }

    public RPCUserlistGetChannelUsersRequest clear() {
      requestingUserId = "";
      channelId = "";
      size = 0L;
      from = 0L;
      excludeOffline = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.requestingUserId.equals("")) {
        output.writeString(1, this.requestingUserId);
      }
      if (!this.channelId.equals("")) {
        output.writeString(2, this.channelId);
      }
      if (this.size != 0L) {
        output.writeInt64(3, this.size);
      }
      if (this.from != 0L) {
        output.writeInt64(4, this.from);
      }
      if (this.excludeOffline != false) {
        output.writeBool(5, this.excludeOffline);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.requestingUserId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.requestingUserId);
      }
      if (!this.channelId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.channelId);
      }
      if (this.size != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.size);
      }
      if (this.from != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.from);
      }
      if (this.excludeOffline != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(5, this.excludeOffline);
      }
      return size;
    }

    @Override
    public RPCUserlistGetChannelUsersRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.requestingUserId = input.readString();
            break;
          }
          case 18: {
            this.channelId = input.readString();
            break;
          }
          case 24: {
            this.size = input.readInt64();
            break;
          }
          case 32: {
            this.from = input.readInt64();
            break;
          }
          case 40: {
            this.excludeOffline = input.readBool();
            break;
          }
        }
      }
    }

    public static RPCUserlistGetChannelUsersRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RPCUserlistGetChannelUsersRequest(), data);
    }

    public static RPCUserlistGetChannelUsersRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RPCUserlistGetChannelUsersRequest().mergeFrom(input);
    }
  }

  public static final class RPCUserlistGetChannelUsersResponse extends
      com.google.protobuf.nano.MessageNano {

    // enum ErrorType
    @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.SOURCE)
    @android.support.annotation.IntDef({
      NONE,
      UNKNOWN_ERROR,
      BAD_REQUEST,
      FORBIDDEN,
    })
    public @interface ErrorType {
    }

    public static final int NONE = 0;
    public static final int UNKNOWN_ERROR = 1;
    public static final int BAD_REQUEST = 2;
    public static final int FORBIDDEN = 3;

    private static volatile RPCUserlistGetChannelUsersResponse[] _emptyArray;
    public static RPCUserlistGetChannelUsersResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RPCUserlistGetChannelUsersResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .proto.RPCUserlistGetChannelUsersResponse.ErrorType error = 1;
    @maple.proto.nano.Userlist.RPCUserlistGetChannelUsersResponse.ErrorType
    public int error;

    // optional int64 total_users = 2;
    public long totalUsers;

    // optional int64 from = 3;
    public long from;

    // repeated .proto.ChannelUser users = 4;
    public maple.proto.nano.Profile.ChannelUser[] users;

    // optional int64 online_users = 5;
    public long onlineUsers;

    // optional int64 paged_users = 6;
    public long pagedUsers;

    public RPCUserlistGetChannelUsersResponse() {
      clear();
    }

    public RPCUserlistGetChannelUsersResponse clear() {
      error = maple.proto.nano.Userlist.RPCUserlistGetChannelUsersResponse.NONE;
      totalUsers = 0L;
      from = 0L;
      users = maple.proto.nano.Profile.ChannelUser.emptyArray();
      onlineUsers = 0L;
      pagedUsers = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.error != maple.proto.nano.Userlist.RPCUserlistGetChannelUsersResponse.NONE) {
        output.writeInt32(1, this.error);
      }
      if (this.totalUsers != 0L) {
        output.writeInt64(2, this.totalUsers);
      }
      if (this.from != 0L) {
        output.writeInt64(3, this.from);
      }
      if (this.users != null && this.users.length > 0) {
        for (int i = 0; i < this.users.length; i++) {
          maple.proto.nano.Profile.ChannelUser element = this.users[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      if (this.onlineUsers != 0L) {
        output.writeInt64(5, this.onlineUsers);
      }
      if (this.pagedUsers != 0L) {
        output.writeInt64(6, this.pagedUsers);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.error != maple.proto.nano.Userlist.RPCUserlistGetChannelUsersResponse.NONE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.error);
      }
      if (this.totalUsers != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.totalUsers);
      }
      if (this.from != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.from);
      }
      if (this.users != null && this.users.length > 0) {
        for (int i = 0; i < this.users.length; i++) {
          maple.proto.nano.Profile.ChannelUser element = this.users[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      if (this.onlineUsers != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(5, this.onlineUsers);
      }
      if (this.pagedUsers != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(6, this.pagedUsers);
      }
      return size;
    }

    @Override
    public RPCUserlistGetChannelUsersResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case maple.proto.nano.Userlist.RPCUserlistGetChannelUsersResponse.NONE:
              case maple.proto.nano.Userlist.RPCUserlistGetChannelUsersResponse.UNKNOWN_ERROR:
              case maple.proto.nano.Userlist.RPCUserlistGetChannelUsersResponse.BAD_REQUEST:
              case maple.proto.nano.Userlist.RPCUserlistGetChannelUsersResponse.FORBIDDEN:
                this.error = value;
                break;
            }
            break;
          }
          case 16: {
            this.totalUsers = input.readInt64();
            break;
          }
          case 24: {
            this.from = input.readInt64();
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.users == null ? 0 : this.users.length;
            maple.proto.nano.Profile.ChannelUser[] newArray =
                new maple.proto.nano.Profile.ChannelUser[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.users, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new maple.proto.nano.Profile.ChannelUser();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new maple.proto.nano.Profile.ChannelUser();
            input.readMessage(newArray[i]);
            this.users = newArray;
            break;
          }
          case 40: {
            this.onlineUsers = input.readInt64();
            break;
          }
          case 48: {
            this.pagedUsers = input.readInt64();
            break;
          }
        }
      }
    }

    public static RPCUserlistGetChannelUsersResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RPCUserlistGetChannelUsersResponse(), data);
    }

    public static RPCUserlistGetChannelUsersResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RPCUserlistGetChannelUsersResponse().mergeFrom(input);
    }
  }

  public static final class RPCUserlistGetHubMembersRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RPCUserlistGetHubMembersRequest[] _emptyArray;
    public static RPCUserlistGetHubMembersRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RPCUserlistGetHubMembersRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string requesting_user_id = 1;
    public java.lang.String requestingUserId;

    // optional string hub_id = 2;
    public java.lang.String hubId;

    // optional int64 size = 3;
    public long size;

    // optional int64 from = 4;
    public long from;

    public RPCUserlistGetHubMembersRequest() {
      clear();
    }

    public RPCUserlistGetHubMembersRequest clear() {
      requestingUserId = "";
      hubId = "";
      size = 0L;
      from = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.requestingUserId.equals("")) {
        output.writeString(1, this.requestingUserId);
      }
      if (!this.hubId.equals("")) {
        output.writeString(2, this.hubId);
      }
      if (this.size != 0L) {
        output.writeInt64(3, this.size);
      }
      if (this.from != 0L) {
        output.writeInt64(4, this.from);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.requestingUserId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.requestingUserId);
      }
      if (!this.hubId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.hubId);
      }
      if (this.size != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.size);
      }
      if (this.from != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.from);
      }
      return size;
    }

    @Override
    public RPCUserlistGetHubMembersRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.requestingUserId = input.readString();
            break;
          }
          case 18: {
            this.hubId = input.readString();
            break;
          }
          case 24: {
            this.size = input.readInt64();
            break;
          }
          case 32: {
            this.from = input.readInt64();
            break;
          }
        }
      }
    }

    public static RPCUserlistGetHubMembersRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RPCUserlistGetHubMembersRequest(), data);
    }

    public static RPCUserlistGetHubMembersRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RPCUserlistGetHubMembersRequest().mergeFrom(input);
    }
  }

  public static final class RPCUserlistGetHubMembersResponse extends
      com.google.protobuf.nano.MessageNano {

    // enum ErrorType
    @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.SOURCE)
    @android.support.annotation.IntDef({
      NONE,
      UNKNOWN_ERROR,
      BAD_REQUEST,
      FORBIDDEN,
    })
    public @interface ErrorType {
    }

    public static final int NONE = 0;
    public static final int UNKNOWN_ERROR = 1;
    public static final int BAD_REQUEST = 2;
    public static final int FORBIDDEN = 3;

    private static volatile RPCUserlistGetHubMembersResponse[] _emptyArray;
    public static RPCUserlistGetHubMembersResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RPCUserlistGetHubMembersResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .proto.RPCUserlistGetHubMembersResponse.ErrorType error = 1;
    @maple.proto.nano.Userlist.RPCUserlistGetHubMembersResponse.ErrorType
    public int error;

    // optional int64 total_users = 2;
    public long totalUsers;

    // optional int64 from = 3;
    public long from;

    // repeated .proto.MembershipEntry users = 4;
    public maple.proto.nano.Community.MembershipEntry[] users;

    // optional int64 paged_users = 6;
    public long pagedUsers;

    public RPCUserlistGetHubMembersResponse() {
      clear();
    }

    public RPCUserlistGetHubMembersResponse clear() {
      error = maple.proto.nano.Userlist.RPCUserlistGetHubMembersResponse.NONE;
      totalUsers = 0L;
      from = 0L;
      users = maple.proto.nano.Community.MembershipEntry.emptyArray();
      pagedUsers = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.error != maple.proto.nano.Userlist.RPCUserlistGetHubMembersResponse.NONE) {
        output.writeInt32(1, this.error);
      }
      if (this.totalUsers != 0L) {
        output.writeInt64(2, this.totalUsers);
      }
      if (this.from != 0L) {
        output.writeInt64(3, this.from);
      }
      if (this.users != null && this.users.length > 0) {
        for (int i = 0; i < this.users.length; i++) {
          maple.proto.nano.Community.MembershipEntry element = this.users[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      if (this.pagedUsers != 0L) {
        output.writeInt64(6, this.pagedUsers);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.error != maple.proto.nano.Userlist.RPCUserlistGetHubMembersResponse.NONE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.error);
      }
      if (this.totalUsers != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.totalUsers);
      }
      if (this.from != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.from);
      }
      if (this.users != null && this.users.length > 0) {
        for (int i = 0; i < this.users.length; i++) {
          maple.proto.nano.Community.MembershipEntry element = this.users[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      if (this.pagedUsers != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(6, this.pagedUsers);
      }
      return size;
    }

    @Override
    public RPCUserlistGetHubMembersResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case maple.proto.nano.Userlist.RPCUserlistGetHubMembersResponse.NONE:
              case maple.proto.nano.Userlist.RPCUserlistGetHubMembersResponse.UNKNOWN_ERROR:
              case maple.proto.nano.Userlist.RPCUserlistGetHubMembersResponse.BAD_REQUEST:
              case maple.proto.nano.Userlist.RPCUserlistGetHubMembersResponse.FORBIDDEN:
                this.error = value;
                break;
            }
            break;
          }
          case 16: {
            this.totalUsers = input.readInt64();
            break;
          }
          case 24: {
            this.from = input.readInt64();
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.users == null ? 0 : this.users.length;
            maple.proto.nano.Community.MembershipEntry[] newArray =
                new maple.proto.nano.Community.MembershipEntry[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.users, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new maple.proto.nano.Community.MembershipEntry();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new maple.proto.nano.Community.MembershipEntry();
            input.readMessage(newArray[i]);
            this.users = newArray;
            break;
          }
          case 48: {
            this.pagedUsers = input.readInt64();
            break;
          }
        }
      }
    }

    public static RPCUserlistGetHubMembersResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RPCUserlistGetHubMembersResponse(), data);
    }

    public static RPCUserlistGetHubMembersResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RPCUserlistGetHubMembersResponse().mergeFrom(input);
    }
  }

  public static final class RPCUserlistSearchHubMembersRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RPCUserlistSearchHubMembersRequest[] _emptyArray;
    public static RPCUserlistSearchHubMembersRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RPCUserlistSearchHubMembersRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string requesting_user_id = 1;
    public java.lang.String requestingUserId;

    // optional string hub_id = 2;
    public java.lang.String hubId;

    // optional int64 size = 3;
    public long size;

    // optional int64 from = 4;
    public long from;

    // optional string term = 5;
    public java.lang.String term;

    // optional bool fuzzy = 6;
    public boolean fuzzy;

    public RPCUserlistSearchHubMembersRequest() {
      clear();
    }

    public RPCUserlistSearchHubMembersRequest clear() {
      requestingUserId = "";
      hubId = "";
      size = 0L;
      from = 0L;
      term = "";
      fuzzy = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.requestingUserId.equals("")) {
        output.writeString(1, this.requestingUserId);
      }
      if (!this.hubId.equals("")) {
        output.writeString(2, this.hubId);
      }
      if (this.size != 0L) {
        output.writeInt64(3, this.size);
      }
      if (this.from != 0L) {
        output.writeInt64(4, this.from);
      }
      if (!this.term.equals("")) {
        output.writeString(5, this.term);
      }
      if (this.fuzzy != false) {
        output.writeBool(6, this.fuzzy);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.requestingUserId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.requestingUserId);
      }
      if (!this.hubId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.hubId);
      }
      if (this.size != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.size);
      }
      if (this.from != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.from);
      }
      if (!this.term.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.term);
      }
      if (this.fuzzy != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(6, this.fuzzy);
      }
      return size;
    }

    @Override
    public RPCUserlistSearchHubMembersRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.requestingUserId = input.readString();
            break;
          }
          case 18: {
            this.hubId = input.readString();
            break;
          }
          case 24: {
            this.size = input.readInt64();
            break;
          }
          case 32: {
            this.from = input.readInt64();
            break;
          }
          case 42: {
            this.term = input.readString();
            break;
          }
          case 48: {
            this.fuzzy = input.readBool();
            break;
          }
        }
      }
    }

    public static RPCUserlistSearchHubMembersRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RPCUserlistSearchHubMembersRequest(), data);
    }

    public static RPCUserlistSearchHubMembersRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RPCUserlistSearchHubMembersRequest().mergeFrom(input);
    }
  }

  public static final class RPCUserlistSearchHubMembersResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RPCUserlistSearchHubMembersResponse[] _emptyArray;
    public static RPCUserlistSearchHubMembersResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RPCUserlistSearchHubMembersResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .proto.SearchMembersResponse.ErrorType error = 1;
    @maple.proto.nano.Community.SearchMembersResponse.ErrorType
    public int error;

    // optional int64 from = 2;
    public long from;

    // repeated .proto.MembershipEntry users = 3;
    public maple.proto.nano.Community.MembershipEntry[] users;

    // optional int64 paged_users = 4;
    public long pagedUsers;

    public RPCUserlistSearchHubMembersResponse() {
      clear();
    }

    public RPCUserlistSearchHubMembersResponse clear() {
      error = maple.proto.nano.Community.SearchMembersResponse.NONE;
      from = 0L;
      users = maple.proto.nano.Community.MembershipEntry.emptyArray();
      pagedUsers = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.error != maple.proto.nano.Community.SearchMembersResponse.NONE) {
        output.writeInt32(1, this.error);
      }
      if (this.from != 0L) {
        output.writeInt64(2, this.from);
      }
      if (this.users != null && this.users.length > 0) {
        for (int i = 0; i < this.users.length; i++) {
          maple.proto.nano.Community.MembershipEntry element = this.users[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      if (this.pagedUsers != 0L) {
        output.writeInt64(4, this.pagedUsers);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.error != maple.proto.nano.Community.SearchMembersResponse.NONE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.error);
      }
      if (this.from != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.from);
      }
      if (this.users != null && this.users.length > 0) {
        for (int i = 0; i < this.users.length; i++) {
          maple.proto.nano.Community.MembershipEntry element = this.users[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      if (this.pagedUsers != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.pagedUsers);
      }
      return size;
    }

    @Override
    public RPCUserlistSearchHubMembersResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case maple.proto.nano.Community.SearchMembersResponse.NONE:
              case maple.proto.nano.Community.SearchMembersResponse.UNKNOWN_ERROR:
              case maple.proto.nano.Community.SearchMembersResponse.BAD_REQUEST:
              case maple.proto.nano.Community.SearchMembersResponse.FORBIDDEN:
                this.error = value;
                break;
            }
            break;
          }
          case 16: {
            this.from = input.readInt64();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.users == null ? 0 : this.users.length;
            maple.proto.nano.Community.MembershipEntry[] newArray =
                new maple.proto.nano.Community.MembershipEntry[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.users, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new maple.proto.nano.Community.MembershipEntry();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new maple.proto.nano.Community.MembershipEntry();
            input.readMessage(newArray[i]);
            this.users = newArray;
            break;
          }
          case 32: {
            this.pagedUsers = input.readInt64();
            break;
          }
        }
      }
    }

    public static RPCUserlistSearchHubMembersResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RPCUserlistSearchHubMembersResponse(), data);
    }

    public static RPCUserlistSearchHubMembersResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RPCUserlistSearchHubMembersResponse().mergeFrom(input);
    }
  }

  public static final class RPCUserlistGetUserCountsRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RPCUserlistGetUserCountsRequest[] _emptyArray;
    public static RPCUserlistGetUserCountsRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RPCUserlistGetUserCountsRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string requesting_user_id = 1;
    public java.lang.String requestingUserId;

    // repeated string hub_ids = 2;
    public java.lang.String[] hubIds;

    // optional bool exclude_offline = 3;
    public boolean excludeOffline;

    public RPCUserlistGetUserCountsRequest() {
      clear();
    }

    public RPCUserlistGetUserCountsRequest clear() {
      requestingUserId = "";
      hubIds = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      excludeOffline = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.requestingUserId.equals("")) {
        output.writeString(1, this.requestingUserId);
      }
      if (this.hubIds != null && this.hubIds.length > 0) {
        for (int i = 0; i < this.hubIds.length; i++) {
          java.lang.String element = this.hubIds[i];
          if (element != null) {
            output.writeString(2, element);
          }
        }
      }
      if (this.excludeOffline != false) {
        output.writeBool(3, this.excludeOffline);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.requestingUserId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.requestingUserId);
      }
      if (this.hubIds != null && this.hubIds.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.hubIds.length; i++) {
          java.lang.String element = this.hubIds[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      if (this.excludeOffline != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(3, this.excludeOffline);
      }
      return size;
    }

    @Override
    public RPCUserlistGetUserCountsRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.requestingUserId = input.readString();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.hubIds == null ? 0 : this.hubIds.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.hubIds, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.hubIds = newArray;
            break;
          }
          case 24: {
            this.excludeOffline = input.readBool();
            break;
          }
        }
      }
    }

    public static RPCUserlistGetUserCountsRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RPCUserlistGetUserCountsRequest(), data);
    }

    public static RPCUserlistGetUserCountsRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RPCUserlistGetUserCountsRequest().mergeFrom(input);
    }
  }

  public static final class RPCUserlistGetUserCountsResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RPCUserlistGetUserCountsResponse[] _emptyArray;
    public static RPCUserlistGetUserCountsResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RPCUserlistGetUserCountsResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // map<string, int64> counts = 1;
    public java.util.Map<java.lang.String, java.lang.Long> counts;

    public RPCUserlistGetUserCountsResponse() {
      clear();
    }

    public RPCUserlistGetUserCountsResponse clear() {
      counts = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.counts != null) {
        com.google.protobuf.nano.InternalNano.serializeMapField(
          output, this.counts, 1,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_INT64);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.counts != null) {
        size += com.google.protobuf.nano.InternalNano.computeMapFieldSize(
          this.counts, 1,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_INT64);
      }
      return size;
    }

    @Override
    public RPCUserlistGetUserCountsResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      com.google.protobuf.nano.MapFactories.MapFactory mapFactory =
        com.google.protobuf.nano.MapFactories.getMapFactory();
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.counts = com.google.protobuf.nano.InternalNano.mergeMapEntry(
              input, this.counts, mapFactory,
              com.google.protobuf.nano.InternalNano.TYPE_STRING,
              com.google.protobuf.nano.InternalNano.TYPE_INT64,
              null,
              10, 16);

            break;
          }
        }
      }
    }

    public static RPCUserlistGetUserCountsResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RPCUserlistGetUserCountsResponse(), data);
    }

    public static RPCUserlistGetUserCountsResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RPCUserlistGetUserCountsResponse().mergeFrom(input);
    }
  }
}
