// Code generated by protoc-gen-go.
// source: contacts.proto
// DO NOT EDIT!

package gosuproto

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type UserAddContactResponse_ErrorType int32

const (
	UserAddContactResponse_NONE          UserAddContactResponse_ErrorType = 0
	UserAddContactResponse_UNKNOWN_ERROR UserAddContactResponse_ErrorType = 1
	UserAddContactResponse_BAD_REQUEST   UserAddContactResponse_ErrorType = 2
)

var UserAddContactResponse_ErrorType_name = map[int32]string{
	0: "NONE",
	1: "UNKNOWN_ERROR",
	2: "BAD_REQUEST",
}
var UserAddContactResponse_ErrorType_value = map[string]int32{
	"NONE":          0,
	"UNKNOWN_ERROR": 1,
	"BAD_REQUEST":   2,
}

func (x UserAddContactResponse_ErrorType) String() string {
	return proto.EnumName(UserAddContactResponse_ErrorType_name, int32(x))
}

type UserRemoveContactResponse_ErrorType int32

const (
	UserRemoveContactResponse_NONE          UserRemoveContactResponse_ErrorType = 0
	UserRemoveContactResponse_UNKNOWN_ERROR UserRemoveContactResponse_ErrorType = 1
	UserRemoveContactResponse_BAD_REQUEST   UserRemoveContactResponse_ErrorType = 2
)

var UserRemoveContactResponse_ErrorType_name = map[int32]string{
	0: "NONE",
	1: "UNKNOWN_ERROR",
	2: "BAD_REQUEST",
}
var UserRemoveContactResponse_ErrorType_value = map[string]int32{
	"NONE":          0,
	"UNKNOWN_ERROR": 1,
	"BAD_REQUEST":   2,
}

func (x UserRemoveContactResponse_ErrorType) String() string {
	return proto.EnumName(UserRemoveContactResponse_ErrorType_name, int32(x))
}

type UserGetContactsResponse_ErrorType int32

const (
	UserGetContactsResponse_NONE          UserGetContactsResponse_ErrorType = 0
	UserGetContactsResponse_UNKNOWN_ERROR UserGetContactsResponse_ErrorType = 1
)

var UserGetContactsResponse_ErrorType_name = map[int32]string{
	0: "NONE",
	1: "UNKNOWN_ERROR",
}
var UserGetContactsResponse_ErrorType_value = map[string]int32{
	"NONE":          0,
	"UNKNOWN_ERROR": 1,
}

func (x UserGetContactsResponse_ErrorType) String() string {
	return proto.EnumName(UserGetContactsResponse_ErrorType_name, int32(x))
}

type RPCUserAddContactRequest struct {
	UserId    string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	ContactId string `protobuf:"bytes,2,opt,name=contact_id" json:"contact_id,omitempty"`
	Mutual    bool   `protobuf:"varint,3,opt,name=mutual" json:"mutual,omitempty"`
}

func (m *RPCUserAddContactRequest) Reset()         { *m = RPCUserAddContactRequest{} }
func (m *RPCUserAddContactRequest) String() string { return proto.CompactTextString(m) }
func (*RPCUserAddContactRequest) ProtoMessage()    {}

type RPCUserAddContactResponse struct {
	Error UserAddContactResponse_ErrorType `protobuf:"varint,1,opt,name=error,enum=proto.UserAddContactResponse_ErrorType" json:"error,omitempty"`
}

func (m *RPCUserAddContactResponse) Reset()         { *m = RPCUserAddContactResponse{} }
func (m *RPCUserAddContactResponse) String() string { return proto.CompactTextString(m) }
func (*RPCUserAddContactResponse) ProtoMessage()    {}

type RPCUserRemoveContactRequest struct {
	UserId    string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
	ContactId string `protobuf:"bytes,2,opt,name=contact_id" json:"contact_id,omitempty"`
}

func (m *RPCUserRemoveContactRequest) Reset()         { *m = RPCUserRemoveContactRequest{} }
func (m *RPCUserRemoveContactRequest) String() string { return proto.CompactTextString(m) }
func (*RPCUserRemoveContactRequest) ProtoMessage()    {}

type RPCUserRemoveContactResponse struct {
	Error UserRemoveContactResponse_ErrorType `protobuf:"varint,1,opt,name=error,enum=proto.UserRemoveContactResponse_ErrorType" json:"error,omitempty"`
}

func (m *RPCUserRemoveContactResponse) Reset()         { *m = RPCUserRemoveContactResponse{} }
func (m *RPCUserRemoveContactResponse) String() string { return proto.CompactTextString(m) }
func (*RPCUserRemoveContactResponse) ProtoMessage()    {}

type RPCUserGetContactsRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (m *RPCUserGetContactsRequest) Reset()         { *m = RPCUserGetContactsRequest{} }
func (m *RPCUserGetContactsRequest) String() string { return proto.CompactTextString(m) }
func (*RPCUserGetContactsRequest) ProtoMessage()    {}

type RPCUserGetContactsResponse struct {
	Error    UserGetContactsResponse_ErrorType `protobuf:"varint,1,opt,name=error,enum=proto.UserGetContactsResponse_ErrorType" json:"error,omitempty"`
	Contacts []*Contact                        `protobuf:"bytes,2,rep,name=contacts" json:"contacts,omitempty"`
}

func (m *RPCUserGetContactsResponse) Reset()         { *m = RPCUserGetContactsResponse{} }
func (m *RPCUserGetContactsResponse) String() string { return proto.CompactTextString(m) }
func (*RPCUserGetContactsResponse) ProtoMessage()    {}

func (m *RPCUserGetContactsResponse) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type UserAddContactRequest struct {
	ContactId string `protobuf:"bytes,1,opt,name=contact_id" json:"contact_id,omitempty"`
	Mutual    bool   `protobuf:"varint,2,opt,name=mutual" json:"mutual,omitempty"`
}

func (m *UserAddContactRequest) Reset()         { *m = UserAddContactRequest{} }
func (m *UserAddContactRequest) String() string { return proto.CompactTextString(m) }
func (*UserAddContactRequest) ProtoMessage()    {}

type UserAddContactResponse struct {
	Error UserAddContactResponse_ErrorType `protobuf:"varint,1,opt,name=error,enum=proto.UserAddContactResponse_ErrorType" json:"error,omitempty"`
}

func (m *UserAddContactResponse) Reset()         { *m = UserAddContactResponse{} }
func (m *UserAddContactResponse) String() string { return proto.CompactTextString(m) }
func (*UserAddContactResponse) ProtoMessage()    {}

type UserRemoveContactResponse struct {
	Error UserRemoveContactResponse_ErrorType `protobuf:"varint,1,opt,name=error,enum=proto.UserRemoveContactResponse_ErrorType" json:"error,omitempty"`
}

func (m *UserRemoveContactResponse) Reset()         { *m = UserRemoveContactResponse{} }
func (m *UserRemoveContactResponse) String() string { return proto.CompactTextString(m) }
func (*UserRemoveContactResponse) ProtoMessage()    {}

type UserGetContactsResponse struct {
	Error    UserGetContactsResponse_ErrorType `protobuf:"varint,1,opt,name=error,enum=proto.UserGetContactsResponse_ErrorType" json:"error,omitempty"`
	Contacts []*Contact                        `protobuf:"bytes,2,rep,name=contacts" json:"contacts,omitempty"`
}

func (m *UserGetContactsResponse) Reset()         { *m = UserGetContactsResponse{} }
func (m *UserGetContactsResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetContactsResponse) ProtoMessage()    {}

func (m *UserGetContactsResponse) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type Contact struct {
	User *ChatUser `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}

func (m *Contact) GetUser() *ChatUser {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.UserAddContactResponse_ErrorType", UserAddContactResponse_ErrorType_name, UserAddContactResponse_ErrorType_value)
	proto.RegisterEnum("proto.UserRemoveContactResponse_ErrorType", UserRemoveContactResponse_ErrorType_name, UserRemoveContactResponse_ErrorType_value)
	proto.RegisterEnum("proto.UserGetContactsResponse_ErrorType", UserGetContactsResponse_ErrorType_name, UserGetContactsResponse_ErrorType_value)
}
