// Code generated by protoc-gen-go.
// source: prefs.proto
// DO NOT EDIT!

package gosuproto

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type PrefNullValue int32

const (
	// Null value.
	PrefNullValue_NULL_VALUE PrefNullValue = 0
)

var PrefNullValue_name = map[int32]string{
	0: "NULL_VALUE",
}
var PrefNullValue_value = map[string]int32{
	"NULL_VALUE": 0,
}

func (x PrefNullValue) String() string {
	return proto.EnumName(PrefNullValue_name, int32(x))
}

type PrefValue struct {
	// Represents a null value.
	NullValue PrefNullValue `protobuf:"varint,1,opt,name=null_value,enum=proto.PrefNullValue" json:"null_value,omitempty"`
	// Represents a double value.
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value" json:"number_value,omitempty"`
	// Represents a string value.
	StringValue string `protobuf:"bytes,3,opt,name=string_value" json:"string_value,omitempty"`
	// Represents a boolean value.
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value" json:"bool_value,omitempty"`
}

func (m *PrefValue) Reset()         { *m = PrefValue{} }
func (m *PrefValue) String() string { return proto.CompactTextString(m) }
func (*PrefValue) ProtoMessage()    {}

type Pref struct {
	Domain  string     `protobuf:"bytes,1,opt,name=domain" json:"domain,omitempty"`
	Keypath string     `protobuf:"bytes,2,opt,name=keypath" json:"keypath,omitempty"`
	Value   *PrefValue `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Pref) Reset()         { *m = Pref{} }
func (m *Pref) String() string { return proto.CompactTextString(m) }
func (*Pref) ProtoMessage()    {}

func (m *Pref) GetValue() *PrefValue {
	if m != nil {
		return m.Value
	}
	return nil
}

// used for database
type PrefRecord struct {
	Id      string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId  string     `protobuf:"bytes,2,opt,name=user_id" json:"user_id,omitempty"`
	Domain  string     `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	Keypath string     `protobuf:"bytes,4,opt,name=keypath" json:"keypath,omitempty"`
	Value   *PrefValue `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
}

func (m *PrefRecord) Reset()         { *m = PrefRecord{} }
func (m *PrefRecord) String() string { return proto.CompactTextString(m) }
func (*PrefRecord) ProtoMessage()    {}

func (m *PrefRecord) GetValue() *PrefValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.PrefNullValue", PrefNullValue_name, PrefNullValue_value)
}
