// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Any;
@class AttachmentAction;
@class AttachmentExternalMedia;
@class AttachmentFile;
@class AttachmentImage;
@class AttachmentImageGallery;
@class AttachmentMedia;
@class AttachmentWebsite;
@class ChatUser;
@class MessageAttachment;
@class MessageBatch;
@class MessageBodyAnnotation;
@class MessageBodyAnnotationChannelLinkExtensionInvitation;
@class SystemAction;
@class SystemMessage;
@class TypingStatus;
@class UserAgent;
@class UserMessage;
@class UserVoiceStatusUpdate;
@class Website;
@class WebsocketMessage;
GPB_ENUM_FWD_DECLARE(ChannelMembershipRecord_MembershipType);
GPB_ENUM_FWD_DECLARE(ChannelMembershipRecord_VoiceStatus);
GPB_ENUM_FWD_DECLARE(ChannelUser_ChannelUserType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum WebsocketMessage_MessageType

typedef GPB_ENUM(WebsocketMessage_MessageType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  WebsocketMessage_MessageType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  WebsocketMessage_MessageType_Unknown = 0,
  WebsocketMessage_MessageType_ChatMessage = 1,
  WebsocketMessage_MessageType_UserAction = 2,
  WebsocketMessage_MessageType_SystemMessage = 3,
  WebsocketMessage_MessageType_Ping = 4,
  WebsocketMessage_MessageType_SystemAction = 5,
};

GPBEnumDescriptor *WebsocketMessage_MessageType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL WebsocketMessage_MessageType_IsValidValue(int32_t value);

#pragma mark - Enum MessageBodyAnnotation_SliceType

typedef GPB_ENUM(MessageBodyAnnotation_SliceType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  MessageBodyAnnotation_SliceType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  MessageBodyAnnotation_SliceType_Unknown = 0,
  MessageBodyAnnotation_SliceType_Plaintext = 1,

  /// \@fix ...
  MessageBodyAnnotation_SliceType_UserMention = 2,
  MessageBodyAnnotation_SliceType_WebLink = 3,
  MessageBodyAnnotation_SliceType_ChannelLink = 4,
  MessageBodyAnnotation_SliceType_Email = 5,
  MessageBodyAnnotation_SliceType_Teamspeak = 6,
  MessageBodyAnnotation_SliceType_Question = 7,
};

GPBEnumDescriptor *MessageBodyAnnotation_SliceType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL MessageBodyAnnotation_SliceType_IsValidValue(int32_t value);

#pragma mark - Enum UserMessage_Type

typedef GPB_ENUM(UserMessage_Type) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  UserMessage_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  UserMessage_Type_None = 0,

  /// future types might include website/image/video etc.
  UserMessage_Type_Question = 1,
};

GPBEnumDescriptor *UserMessage_Type_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL UserMessage_Type_IsValidValue(int32_t value);

#pragma mark - Enum MessageAttachment_AttachmentType

typedef GPB_ENUM(MessageAttachment_AttachmentType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  MessageAttachment_AttachmentType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  MessageAttachment_AttachmentType_Unknown = 0,

  /// body string
  MessageAttachment_AttachmentType_Quote = 1,

  /// body AttachmentImage
  MessageAttachment_AttachmentType_Image = 2,

  /// body AttachmentImageGallery
  MessageAttachment_AttachmentType_ImageGallery = 3,

  /// body AttachmentMedia
  MessageAttachment_AttachmentType_Video = 4,

  /// body AttachmentMedia
  MessageAttachment_AttachmentType_Audio = 5,

  /// body AttachmentWebsite
  MessageAttachment_AttachmentType_Website = 6,

  /// body ??
  MessageAttachment_AttachmentType_Embed = 7,

  /// AttachmentFile
  MessageAttachment_AttachmentType_Document = 8,

  /// AttachmentFile
  MessageAttachment_AttachmentType_File = 9,

  /// WebsocketMessage
  MessageAttachment_AttachmentType_Message = 10,

  /// WebsocketMessage
  MessageAttachment_AttachmentType_ReplyTo = 11,

  /// External services with rich attachment support
  MessageAttachment_AttachmentType_ExternalTwitch = 100,

  /// AttachmentExternalMedia
  MessageAttachment_AttachmentType_ExternalYoutube = 101,

  /// AttachmentExternalMedia
  MessageAttachment_AttachmentType_ExternalVimeo = 102,

  /// AttachmentExternalMedia
  MessageAttachment_AttachmentType_ExternalSoundcloud = 103,
};

GPBEnumDescriptor *MessageAttachment_AttachmentType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL MessageAttachment_AttachmentType_IsValidValue(int32_t value);

#pragma mark - Enum Website_WebsiteType

typedef GPB_ENUM(Website_WebsiteType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  Website_WebsiteType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Website_WebsiteType_Default = 0,
  Website_WebsiteType_TwitchChannel = 1,
  Website_WebsiteType_YoutubeVideo = 2,
};

GPBEnumDescriptor *Website_WebsiteType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL Website_WebsiteType_IsValidValue(int32_t value);

#pragma mark - Enum SystemMessage_MessageType

typedef GPB_ENUM(SystemMessage_MessageType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  SystemMessage_MessageType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  SystemMessage_MessageType_Unknown = 0,
  SystemMessage_MessageType_Typing = 1,
  SystemMessage_MessageType_Status = 2,
  SystemMessage_MessageType_SystemMessage = 3,
  SystemMessage_MessageType_UserJoined = 4,
  SystemMessage_MessageType_UserLeft = 5,
  SystemMessage_MessageType_FriendUpdated = 6,
  SystemMessage_MessageType_ReadStatusUpdate = 7,
  SystemMessage_MessageType_RequestToPull = 8,
  SystemMessage_MessageType_UserVoiceStatus = 9,
  SystemMessage_MessageType_MessageDeleted = 10,
  SystemMessage_MessageType_MessageBatchDeleted = 11,
};

GPBEnumDescriptor *SystemMessage_MessageType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL SystemMessage_MessageType_IsValidValue(int32_t value);

#pragma mark - Enum SystemAction_Type

typedef GPB_ENUM(SystemAction_Type) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  SystemAction_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  SystemAction_Type_Unknown = 0,
  SystemAction_Type_General = 1,
  SystemAction_Type_UserLoggedIn = 2,
  SystemAction_Type_Donation = 3,
};

GPBEnumDescriptor *SystemAction_Type_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL SystemAction_Type_IsValidValue(int32_t value);

#pragma mark - MessageRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface MessageRoot : GPBRootObject
@end

#pragma mark - WebsocketMessage

typedef GPB_ENUM(WebsocketMessage_FieldNumber) {
  WebsocketMessage_FieldNumber_Id_p = 1,
  WebsocketMessage_FieldNumber_Type = 2,
  WebsocketMessage_FieldNumber_Timestamp = 3,
  WebsocketMessage_FieldNumber_Channel = 4,
  WebsocketMessage_FieldNumber_Sender = 5,
  WebsocketMessage_FieldNumber_UserMessage = 6,
  WebsocketMessage_FieldNumber_UserAction = 7,
  WebsocketMessage_FieldNumber_SystemMessage = 8,
  WebsocketMessage_FieldNumber_Recipient = 9,
  WebsocketMessage_FieldNumber_SystemAction = 10,
  WebsocketMessage_FieldNumber_RecipientsArray = 11,
  WebsocketMessage_FieldNumber_ProcessedByCrawler = 16,
  WebsocketMessage_FieldNumber_Deleted = 17,
};

typedef GPB_ENUM(WebsocketMessage_Message_OneOfCase) {
  WebsocketMessage_Message_OneOfCase_GPBUnsetOneOfCase = 0,
  WebsocketMessage_Message_OneOfCase_UserMessage = 6,
  WebsocketMessage_Message_OneOfCase_UserAction = 7,
  WebsocketMessage_Message_OneOfCase_SystemMessage = 8,
  WebsocketMessage_Message_OneOfCase_SystemAction = 10,
};

@interface WebsocketMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) WebsocketMessage_MessageType type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

@property(nonatomic, readonly) WebsocketMessage_Message_OneOfCase messageOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) UserMessage *userMessage;

@property(nonatomic, readwrite, strong, null_resettable) UserMessage *userAction;

@property(nonatomic, readwrite, strong, null_resettable) SystemMessage *systemMessage;

@property(nonatomic, readwrite, strong, null_resettable) SystemAction *systemAction;

/// this field is deprecated => use recipients field
@property(nonatomic, readwrite, copy, null_resettable) NSString *recipient;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *recipientsArray;
/// The number of items in @c recipientsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger recipientsArray_Count;

@property(nonatomic, readwrite) BOOL processedByCrawler;

@property(nonatomic, readwrite) BOOL deleted;

@end

/// Fetches the raw value of a @c WebsocketMessage's @c type property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t WebsocketMessage_Type_RawValue(WebsocketMessage *message);
/// Sets the raw value of an @c WebsocketMessage's @c type property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetWebsocketMessage_Type_RawValue(WebsocketMessage *message, int32_t value);

/// Clears whatever value was set for the oneof 'message'.
void WebsocketMessage_ClearMessageOneOfCase(WebsocketMessage *message);

#pragma mark - MessageBodyAnnotation

typedef GPB_ENUM(MessageBodyAnnotation_FieldNumber) {
  MessageBodyAnnotation_FieldNumber_Type = 1,
  MessageBodyAnnotation_FieldNumber_PosStart = 2,
  MessageBodyAnnotation_FieldNumber_PosEnd = 3,
  MessageBodyAnnotation_FieldNumber_Replacement = 4,
  MessageBodyAnnotation_FieldNumber_Target = 5,
  MessageBodyAnnotation_FieldNumber_Proprietary = 6,
};

@interface MessageBodyAnnotation : GPBMessage

@property(nonatomic, readwrite) MessageBodyAnnotation_SliceType type;

@property(nonatomic, readwrite) int32_t posStart;

@property(nonatomic, readwrite) int32_t posEnd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *replacement;

@property(nonatomic, readwrite, copy, null_resettable) NSString *target;

@property(nonatomic, readwrite, copy, null_resettable) NSData *proprietary;

@end

/// Fetches the raw value of a @c MessageBodyAnnotation's @c type property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t MessageBodyAnnotation_Type_RawValue(MessageBodyAnnotation *message);
/// Sets the raw value of an @c MessageBodyAnnotation's @c type property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetMessageBodyAnnotation_Type_RawValue(MessageBodyAnnotation *message, int32_t value);

#pragma mark - MessageBodyAnnotationChannelLinkExtension

typedef GPB_ENUM(MessageBodyAnnotationChannelLinkExtension_FieldNumber) {
  MessageBodyAnnotationChannelLinkExtension_FieldNumber_Invitation = 1,
};

@interface MessageBodyAnnotationChannelLinkExtension : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MessageBodyAnnotationChannelLinkExtensionInvitation *invitation;
/// Test to see if @c invitation has been set.
@property(nonatomic, readwrite) BOOL hasInvitation;

@end

#pragma mark - MessageBodyAnnotationChannelLinkExtensionInvitation

typedef GPB_ENUM(MessageBodyAnnotationChannelLinkExtensionInvitation_FieldNumber) {
  MessageBodyAnnotationChannelLinkExtensionInvitation_FieldNumber_Consumed = 1,
};

@interface MessageBodyAnnotationChannelLinkExtensionInvitation : GPBMessage

@property(nonatomic, readwrite) BOOL consumed;

@end

#pragma mark - UserMessage

typedef GPB_ENUM(UserMessage_FieldNumber) {
  UserMessage_FieldNumber_Body = 1,
  UserMessage_FieldNumber_BodyAnnotationsArray = 2,
  UserMessage_FieldNumber_User = 3,
  UserMessage_FieldNumber_DeletedTimestamp = 4,
  UserMessage_FieldNumber_DeletedUser = 5,
  UserMessage_FieldNumber_Type = 6,
  UserMessage_FieldNumber_ConversationId = 7,
  UserMessage_FieldNumber_Quote = 16,
  UserMessage_FieldNumber_Website = 17,
  UserMessage_FieldNumber_AttachmentsArray = 18,
};

typedef GPB_ENUM(UserMessage_Extension_OneOfCase) {
  UserMessage_Extension_OneOfCase_GPBUnsetOneOfCase = 0,
  UserMessage_Extension_OneOfCase_Quote = 16,
  UserMessage_Extension_OneOfCase_Website = 17,
};

@interface UserMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *body;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MessageBodyAnnotation*> *bodyAnnotationsArray;
/// The number of items in @c bodyAnnotationsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger bodyAnnotationsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) ChatUser *user;
/// Test to see if @c user has been set.
@property(nonatomic, readwrite) BOOL hasUser;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deletedTimestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deletedUser;

@property(nonatomic, readwrite) UserMessage_Type type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *conversationId;

/// rich message >= 16;
@property(nonatomic, readonly) UserMessage_Extension_OneOfCase extensionOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quote;

@property(nonatomic, readwrite, strong, null_resettable) Website *website;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MessageAttachment*> *attachmentsArray;
/// The number of items in @c attachmentsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger attachmentsArray_Count;

@end

/// Fetches the raw value of a @c UserMessage's @c type property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t UserMessage_Type_RawValue(UserMessage *message);
/// Sets the raw value of an @c UserMessage's @c type property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetUserMessage_Type_RawValue(UserMessage *message, int32_t value);

/// Clears whatever value was set for the oneof 'extension'.
void UserMessage_ClearExtensionOneOfCase(UserMessage *message);

#pragma mark - MessageAttachment

typedef GPB_ENUM(MessageAttachment_FieldNumber) {
  MessageAttachment_FieldNumber_Type = 1,
  MessageAttachment_FieldNumber_PosStart = 2,
  MessageAttachment_FieldNumber_PosEnd = 3,
  MessageAttachment_FieldNumber_FallbackURL = 4,
  MessageAttachment_FieldNumber_ActionsArray = 5,
  MessageAttachment_FieldNumber_Quote = 16,
  MessageAttachment_FieldNumber_Website = 17,
  MessageAttachment_FieldNumber_Image = 18,
  MessageAttachment_FieldNumber_Gallery = 19,
  MessageAttachment_FieldNumber_Media = 20,
  MessageAttachment_FieldNumber_ExternalMedia = 21,
  MessageAttachment_FieldNumber_File = 22,
  MessageAttachment_FieldNumber_Message = 23,
};

typedef GPB_ENUM(MessageAttachment_Body_OneOfCase) {
  MessageAttachment_Body_OneOfCase_GPBUnsetOneOfCase = 0,
  MessageAttachment_Body_OneOfCase_Quote = 16,
  MessageAttachment_Body_OneOfCase_Website = 17,
  MessageAttachment_Body_OneOfCase_Image = 18,
  MessageAttachment_Body_OneOfCase_Gallery = 19,
  MessageAttachment_Body_OneOfCase_Media = 20,
  MessageAttachment_Body_OneOfCase_ExternalMedia = 21,
  MessageAttachment_Body_OneOfCase_File = 22,
  MessageAttachment_Body_OneOfCase_Message = 23,
};

@interface MessageAttachment : GPBMessage

@property(nonatomic, readwrite) MessageAttachment_AttachmentType type;

@property(nonatomic, readwrite) int32_t posStart;

@property(nonatomic, readwrite) int32_t posEnd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fallbackURL;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AttachmentAction*> *actionsArray;
/// The number of items in @c actionsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger actionsArray_Count;

@property(nonatomic, readonly) MessageAttachment_Body_OneOfCase bodyOneOfCase;

/// QUOTE
@property(nonatomic, readwrite, copy, null_resettable) NSString *quote;

/// WEBSITE
@property(nonatomic, readwrite, strong, null_resettable) AttachmentWebsite *website;

/// IMAGE
@property(nonatomic, readwrite, strong, null_resettable) AttachmentImage *image;

/// IMAGE_GALLERY
@property(nonatomic, readwrite, strong, null_resettable) AttachmentImageGallery *gallery;

/// VIDEO, AUDIO
@property(nonatomic, readwrite, strong, null_resettable) AttachmentMedia *media;

/// EXTERNAL_TWITCH, EXTERNAL_YOUTUBE, EXTERNAL_VIMEO, EXTERNAL_SOUNDCLOUD
@property(nonatomic, readwrite, strong, null_resettable) AttachmentExternalMedia *externalMedia;

/// DOCUMENT, FILE
@property(nonatomic, readwrite, strong, null_resettable) AttachmentFile *file;

/// MESSAGE, REPLY_TO
@property(nonatomic, readwrite, strong, null_resettable) WebsocketMessage *message;

@end

/// Fetches the raw value of a @c MessageAttachment's @c type property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t MessageAttachment_Type_RawValue(MessageAttachment *message);
/// Sets the raw value of an @c MessageAttachment's @c type property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetMessageAttachment_Type_RawValue(MessageAttachment *message, int32_t value);

/// Clears whatever value was set for the oneof 'body'.
void MessageAttachment_ClearBodyOneOfCase(MessageAttachment *message);

#pragma mark - AttachmentAction

/// VOID
@interface AttachmentAction : GPBMessage

@end

#pragma mark - AttachmentWebsite

typedef GPB_ENUM(AttachmentWebsite_FieldNumber) {
  AttachmentWebsite_FieldNumber_URL = 1,
  AttachmentWebsite_FieldNumber_Title = 2,
  AttachmentWebsite_FieldNumber_Description_p = 3,
  AttachmentWebsite_FieldNumber_Favicon = 4,
  AttachmentWebsite_FieldNumber_Image = 16,
  AttachmentWebsite_FieldNumber_Media = 17,
};

@interface AttachmentWebsite : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *favicon;

@property(nonatomic, readwrite, strong, null_resettable) AttachmentImage *image;
/// Test to see if @c image has been set.
@property(nonatomic, readwrite) BOOL hasImage;

@property(nonatomic, readwrite, strong, null_resettable) AttachmentMedia *media;
/// Test to see if @c media has been set.
@property(nonatomic, readwrite) BOOL hasMedia;

@end

#pragma mark - AttachmentImage

typedef GPB_ENUM(AttachmentImage_FieldNumber) {
  AttachmentImage_FieldNumber_URL = 1,
  AttachmentImage_FieldNumber_Width = 2,
  AttachmentImage_FieldNumber_Height = 3,
  AttachmentImage_FieldNumber_Placeholder = 4,
  AttachmentImage_FieldNumber_Caption = 5,
  AttachmentImage_FieldNumber_MimeType = 6,
};

@interface AttachmentImage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) int32_t width;

@property(nonatomic, readwrite) int32_t height;

@property(nonatomic, readwrite, copy, null_resettable) NSData *placeholder;

@property(nonatomic, readwrite, copy, null_resettable) NSString *caption;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mimeType;

@end

#pragma mark - AttachmentImageGallery

typedef GPB_ENUM(AttachmentImageGallery_FieldNumber) {
  AttachmentImageGallery_FieldNumber_ImagesArray = 1,
};

@interface AttachmentImageGallery : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AttachmentImage*> *imagesArray;
/// The number of items in @c imagesArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@end

#pragma mark - AttachmentMedia

typedef GPB_ENUM(AttachmentMedia_FieldNumber) {
  AttachmentMedia_FieldNumber_URL = 1,
  AttachmentMedia_FieldNumber_Width = 2,
  AttachmentMedia_FieldNumber_Height = 3,
  AttachmentMedia_FieldNumber_Placeholder = 4,
  AttachmentMedia_FieldNumber_PreviewURL = 5,
  AttachmentMedia_FieldNumber_MimeType = 6,
};

@interface AttachmentMedia : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) int32_t width;

@property(nonatomic, readwrite) int32_t height;

@property(nonatomic, readwrite, copy, null_resettable) NSData *placeholder;

@property(nonatomic, readwrite, copy, null_resettable) NSString *previewURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mimeType;

@end

#pragma mark - AttachmentExternalMedia

typedef GPB_ENUM(AttachmentExternalMedia_FieldNumber) {
  AttachmentExternalMedia_FieldNumber_URL = 1,
  AttachmentExternalMedia_FieldNumber_Width = 2,
  AttachmentExternalMedia_FieldNumber_Height = 3,
  AttachmentExternalMedia_FieldNumber_Placeholder = 4,
  AttachmentExternalMedia_FieldNumber_PreviewURL = 5,
  AttachmentExternalMedia_FieldNumber_ContentId = 6,
};

@interface AttachmentExternalMedia : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) int32_t width;

@property(nonatomic, readwrite) int32_t height;

@property(nonatomic, readwrite, copy, null_resettable) NSData *placeholder;

@property(nonatomic, readwrite, copy, null_resettable) NSString *previewURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentId;

@end

#pragma mark - AttachmentFile

typedef GPB_ENUM(AttachmentFile_FieldNumber) {
  AttachmentFile_FieldNumber_URL = 1,
  AttachmentFile_FieldNumber_Title = 2,
  AttachmentFile_FieldNumber_Preview = 3,
  AttachmentFile_FieldNumber_MimeType = 4,
  AttachmentFile_FieldNumber_Encoding = 5,
  AttachmentFile_FieldNumber_Size = 6,
};

@interface AttachmentFile : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *preview;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mimeType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *encoding;

@property(nonatomic, readwrite) int64_t size;

@end

#pragma mark - Website

typedef GPB_ENUM(Website_FieldNumber) {
  Website_FieldNumber_URL = 1,
  Website_FieldNumber_Title = 2,
  Website_FieldNumber_Description_p = 3,
  Website_FieldNumber_Image = 4,
  Website_FieldNumber_Video = 5,
  Website_FieldNumber_ImageWidth = 6,
  Website_FieldNumber_ImageHeight = 7,
  Website_FieldNumber_Type = 8,
  Website_FieldNumber_ContentId = 9,
};

@interface Website : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *image;

@property(nonatomic, readwrite, copy, null_resettable) NSString *video;

@property(nonatomic, readwrite) int32_t imageWidth;

@property(nonatomic, readwrite) int32_t imageHeight;

@property(nonatomic, readwrite) Website_WebsiteType type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentId;

@end

/// Fetches the raw value of a @c Website's @c type property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t Website_Type_RawValue(Website *message);
/// Sets the raw value of an @c Website's @c type property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetWebsite_Type_RawValue(Website *message, int32_t value);

#pragma mark - UserAction

typedef GPB_ENUM(UserAction_FieldNumber) {
  UserAction_FieldNumber_Id_p = 1,
  UserAction_FieldNumber_Message = 2,
  UserAction_FieldNumber_UserId = 3,
  UserAction_FieldNumber_Channel = 4,
};

@interface UserAction : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channel;

@end

#pragma mark - SystemMessage

typedef GPB_ENUM(SystemMessage_FieldNumber) {
  SystemMessage_FieldNumber_Type = 1,
  SystemMessage_FieldNumber_Channel = 2,
  SystemMessage_FieldNumber_Typing = 3,
  SystemMessage_FieldNumber_User = 4,
  SystemMessage_FieldNumber_Message = 5,
  SystemMessage_FieldNumber_UserTypeV1 = 6,
  SystemMessage_FieldNumber_UserType = 7,
  SystemMessage_FieldNumber_UserVoiceStatus = 8,
  SystemMessage_FieldNumber_MessageBatch = 9,
  SystemMessage_FieldNumber_Payload = 16,
};

typedef GPB_ENUM(SystemMessage_Body_OneOfCase) {
  SystemMessage_Body_OneOfCase_GPBUnsetOneOfCase = 0,
  SystemMessage_Body_OneOfCase_Typing = 3,
  SystemMessage_Body_OneOfCase_User = 4,
  SystemMessage_Body_OneOfCase_Message = 5,
  SystemMessage_Body_OneOfCase_UserVoiceStatus = 8,
  SystemMessage_Body_OneOfCase_MessageBatch = 9,
};

@interface SystemMessage : GPBMessage

@property(nonatomic, readwrite) SystemMessage_MessageType type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channel;

@property(nonatomic, readonly) SystemMessage_Body_OneOfCase bodyOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) TypingStatus *typing;

@property(nonatomic, readwrite, strong, null_resettable) ChatUser *user;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite, strong, null_resettable) UserVoiceStatusUpdate *userVoiceStatus;

@property(nonatomic, readwrite, strong, null_resettable) MessageBatch *messageBatch;

@property(nonatomic, readwrite) enum ChannelUser_ChannelUserType userTypeV1;

@property(nonatomic, readwrite) enum ChannelMembershipRecord_MembershipType userType;

@property(nonatomic, readwrite, strong, null_resettable) Any *payload;
/// Test to see if @c payload has been set.
@property(nonatomic, readwrite) BOOL hasPayload;

@end

/// Fetches the raw value of a @c SystemMessage's @c type property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t SystemMessage_Type_RawValue(SystemMessage *message);
/// Sets the raw value of an @c SystemMessage's @c type property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetSystemMessage_Type_RawValue(SystemMessage *message, int32_t value);

/// Fetches the raw value of a @c SystemMessage's @c userTypeV1 property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t SystemMessage_UserTypeV1_RawValue(SystemMessage *message);
/// Sets the raw value of an @c SystemMessage's @c userTypeV1 property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetSystemMessage_UserTypeV1_RawValue(SystemMessage *message, int32_t value);

/// Fetches the raw value of a @c SystemMessage's @c userType property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t SystemMessage_UserType_RawValue(SystemMessage *message);
/// Sets the raw value of an @c SystemMessage's @c userType property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetSystemMessage_UserType_RawValue(SystemMessage *message, int32_t value);

/// Clears whatever value was set for the oneof 'body'.
void SystemMessage_ClearBodyOneOfCase(SystemMessage *message);

#pragma mark - SystemAction

typedef GPB_ENUM(SystemAction_FieldNumber) {
  SystemAction_FieldNumber_Type = 1,
  SystemAction_FieldNumber_Body = 2,
  SystemAction_FieldNumber_BodyAnnotationsArray = 3,
  SystemAction_FieldNumber_Payload = 4,
};

@interface SystemAction : GPBMessage

@property(nonatomic, readwrite) SystemAction_Type type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *body;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MessageBodyAnnotation*> *bodyAnnotationsArray;
/// The number of items in @c bodyAnnotationsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger bodyAnnotationsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Any *payload;
/// Test to see if @c payload has been set.
@property(nonatomic, readwrite) BOOL hasPayload;

@end

/// Fetches the raw value of a @c SystemAction's @c type property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t SystemAction_Type_RawValue(SystemAction *message);
/// Sets the raw value of an @c SystemAction's @c type property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetSystemAction_Type_RawValue(SystemAction *message, int32_t value);

#pragma mark - SystemActionPayloadUserLoggedIn

typedef GPB_ENUM(SystemActionPayloadUserLoggedIn_FieldNumber) {
  SystemActionPayloadUserLoggedIn_FieldNumber_FormerUser = 1,
  SystemActionPayloadUserLoggedIn_FieldNumber_CurrentUser = 2,
};

@interface SystemActionPayloadUserLoggedIn : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ChatUser *formerUser;
/// Test to see if @c formerUser has been set.
@property(nonatomic, readwrite) BOOL hasFormerUser;

@property(nonatomic, readwrite, strong, null_resettable) ChatUser *currentUser;
/// Test to see if @c currentUser has been set.
@property(nonatomic, readwrite) BOOL hasCurrentUser;

@end

#pragma mark - MessageBatch

typedef GPB_ENUM(MessageBatch_FieldNumber) {
  MessageBatch_FieldNumber_Start = 1,
  MessageBatch_FieldNumber_End = 2,
};

@interface MessageBatch : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *start;

@property(nonatomic, readwrite, copy, null_resettable) NSString *end;

@end

#pragma mark - UserVoiceStatusUpdate

typedef GPB_ENUM(UserVoiceStatusUpdate_FieldNumber) {
  UserVoiceStatusUpdate_FieldNumber_UserId = 1,
  UserVoiceStatusUpdate_FieldNumber_UserVoiceStatus = 2,
};

@interface UserVoiceStatusUpdate : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) enum ChannelMembershipRecord_VoiceStatus userVoiceStatus;

@end

/// Fetches the raw value of a @c UserVoiceStatusUpdate's @c userVoiceStatus property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t UserVoiceStatusUpdate_UserVoiceStatus_RawValue(UserVoiceStatusUpdate *message);
/// Sets the raw value of an @c UserVoiceStatusUpdate's @c userVoiceStatus property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetUserVoiceStatusUpdate_UserVoiceStatus_RawValue(UserVoiceStatusUpdate *message, int32_t value);

#pragma mark - TypingStatus

typedef GPB_ENUM(TypingStatus_FieldNumber) {
  TypingStatus_FieldNumber_UserId = 1,
  TypingStatus_FieldNumber_IsTyping = 2,
};

@interface TypingStatus : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite) BOOL isTyping;

@end

#pragma mark - MessageWithMeta

typedef GPB_ENUM(MessageWithMeta_FieldNumber) {
  MessageWithMeta_FieldNumber_Message = 1,
  MessageWithMeta_FieldNumber_SenderAgent = 2,
};

@interface MessageWithMeta : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) WebsocketMessage *message;
/// Test to see if @c message has been set.
@property(nonatomic, readwrite) BOOL hasMessage;

@property(nonatomic, readwrite, strong, null_resettable) UserAgent *senderAgent;
/// Test to see if @c senderAgent has been set.
@property(nonatomic, readwrite) BOOL hasSenderAgent;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
