// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nsq.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Nsq.pbobjc.h"
 #import "Profile.pbobjc.h"
 #import "Any.pbobjc.h"
 #import "Message.pbobjc.h"
 #import "HubBase.pbobjc.h"
 #import "Hub.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - NsqRoot

@implementation NsqRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[ProfileRoot extensionRegistry]];
    [registry addExtensions:[AnyRoot extensionRegistry]];
    [registry addExtensions:[MessageRoot extensionRegistry]];
    [registry addExtensions:[HubBaseRoot extensionRegistry]];
    [registry addExtensions:[HubRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - NsqRoot_FileDescriptor

static GPBFileDescriptor *NsqRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"proto"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GroupUpdateWrapper

@implementation GroupUpdateWrapper

@dynamic hasGroup, group;
@dynamic action;

typedef struct GroupUpdateWrapper__storage_ {
  uint32_t _has_storage_[1];
  GroupUpdateWrapper_Action action;
  Group *group;
} GroupUpdateWrapper__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "group",
        .dataTypeSpecific.className = GPBStringifySymbol(Group),
        .number = GroupUpdateWrapper_FieldNumber_Group,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GroupUpdateWrapper__storage_, group),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "action",
        .dataTypeSpecific.enumDescFunc = GroupUpdateWrapper_Action_EnumDescriptor,
        .number = GroupUpdateWrapper_FieldNumber_Action,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GroupUpdateWrapper__storage_, action),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GroupUpdateWrapper class]
                                     rootClass:[NsqRoot class]
                                          file:NsqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GroupUpdateWrapper__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GroupUpdateWrapper_Action_RawValue(GroupUpdateWrapper *message) {
  GPBDescriptor *descriptor = [GroupUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GroupUpdateWrapper_FieldNumber_Action];
  return GPBGetMessageInt32Field(message, field);
}

void SetGroupUpdateWrapper_Action_RawValue(GroupUpdateWrapper *message, int32_t value) {
  GPBDescriptor *descriptor = [GroupUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GroupUpdateWrapper_FieldNumber_Action];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum GroupUpdateWrapper_Action

GPBEnumDescriptor *GroupUpdateWrapper_Action_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Create\000Update\000Delete\000";
    static const int32_t values[] = {
        GroupUpdateWrapper_Action_Unknown,
        GroupUpdateWrapper_Action_Create,
        GroupUpdateWrapper_Action_Update,
        GroupUpdateWrapper_Action_Delete,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GroupUpdateWrapper_Action)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GroupUpdateWrapper_Action_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GroupUpdateWrapper_Action_IsValidValue(int32_t value__) {
  switch (value__) {
    case GroupUpdateWrapper_Action_Unknown:
    case GroupUpdateWrapper_Action_Create:
    case GroupUpdateWrapper_Action_Update:
    case GroupUpdateWrapper_Action_Delete:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - ContentUpdateWrapper

@implementation ContentUpdateWrapper

@dynamic hasData_p, data_p;
@dynamic operation;
@dynamic timestamp;
@dynamic entryId;

typedef struct ContentUpdateWrapper__storage_ {
  uint32_t _has_storage_[1];
  ContentUpdateWrapper_Operation operation;
  Any *data_p;
  NSString *entryId;
  int64_t timestamp;
} ContentUpdateWrapper__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "data_p",
        .dataTypeSpecific.className = GPBStringifySymbol(Any),
        .number = ContentUpdateWrapper_FieldNumber_Data_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ContentUpdateWrapper__storage_, data_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "operation",
        .dataTypeSpecific.enumDescFunc = ContentUpdateWrapper_Operation_EnumDescriptor,
        .number = ContentUpdateWrapper_FieldNumber_Operation,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ContentUpdateWrapper__storage_, operation),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = ContentUpdateWrapper_FieldNumber_Timestamp,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ContentUpdateWrapper__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "entryId",
        .dataTypeSpecific.className = NULL,
        .number = ContentUpdateWrapper_FieldNumber_EntryId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ContentUpdateWrapper__storage_, entryId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ContentUpdateWrapper class]
                                     rootClass:[NsqRoot class]
                                          file:NsqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ContentUpdateWrapper__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t ContentUpdateWrapper_Operation_RawValue(ContentUpdateWrapper *message) {
  GPBDescriptor *descriptor = [ContentUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ContentUpdateWrapper_FieldNumber_Operation];
  return GPBGetMessageInt32Field(message, field);
}

void SetContentUpdateWrapper_Operation_RawValue(ContentUpdateWrapper *message, int32_t value) {
  GPBDescriptor *descriptor = [ContentUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ContentUpdateWrapper_FieldNumber_Operation];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum ContentUpdateWrapper_Operation

GPBEnumDescriptor *ContentUpdateWrapper_Operation_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Create\000Update\000Delete\000";
    static const int32_t values[] = {
        ContentUpdateWrapper_Operation_Unknown,
        ContentUpdateWrapper_Operation_Create,
        ContentUpdateWrapper_Operation_Update,
        ContentUpdateWrapper_Operation_Delete,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(ContentUpdateWrapper_Operation)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:ContentUpdateWrapper_Operation_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL ContentUpdateWrapper_Operation_IsValidValue(int32_t value__) {
  switch (value__) {
    case ContentUpdateWrapper_Operation_Unknown:
    case ContentUpdateWrapper_Operation_Create:
    case ContentUpdateWrapper_Operation_Update:
    case ContentUpdateWrapper_Operation_Delete:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - MessageDeletedEvent

@implementation MessageDeletedEvent

@dynamic messageId;
@dynamic channelId;
@dynamic hasMessageBatch, messageBatch;
@dynamic hasMessagePayload, messagePayload;
@dynamic userId;

typedef struct MessageDeletedEvent__storage_ {
  uint32_t _has_storage_[1];
  NSString *messageId;
  NSString *channelId;
  MessageBatch *messageBatch;
  Any *messagePayload;
  NSString *userId;
} MessageDeletedEvent__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageId",
        .dataTypeSpecific.className = NULL,
        .number = MessageDeletedEvent_FieldNumber_MessageId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MessageDeletedEvent__storage_, messageId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "channelId",
        .dataTypeSpecific.className = NULL,
        .number = MessageDeletedEvent_FieldNumber_ChannelId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MessageDeletedEvent__storage_, channelId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "messageBatch",
        .dataTypeSpecific.className = GPBStringifySymbol(MessageBatch),
        .number = MessageDeletedEvent_FieldNumber_MessageBatch,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MessageDeletedEvent__storage_, messageBatch),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "messagePayload",
        .dataTypeSpecific.className = GPBStringifySymbol(Any),
        .number = MessageDeletedEvent_FieldNumber_MessagePayload,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MessageDeletedEvent__storage_, messagePayload),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = MessageDeletedEvent_FieldNumber_UserId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(MessageDeletedEvent__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MessageDeletedEvent class]
                                     rootClass:[NsqRoot class]
                                          file:NsqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MessageDeletedEvent__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - UserUpdateWrapper

@implementation UserUpdateWrapper

@dynamic timestamp;
@dynamic action;
@dynamic userId;
@dynamic hasUser, user;

typedef struct UserUpdateWrapper__storage_ {
  uint32_t _has_storage_[1];
  UserUpdateWrapper_Action action;
  NSString *userId;
  User *user;
  int64_t timestamp;
} UserUpdateWrapper__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = UserUpdateWrapper_FieldNumber_Timestamp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UserUpdateWrapper__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "action",
        .dataTypeSpecific.enumDescFunc = UserUpdateWrapper_Action_EnumDescriptor,
        .number = UserUpdateWrapper_FieldNumber_Action,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UserUpdateWrapper__storage_, action),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = UserUpdateWrapper_FieldNumber_UserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(UserUpdateWrapper__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(User),
        .number = UserUpdateWrapper_FieldNumber_User,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(UserUpdateWrapper__storage_, user),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UserUpdateWrapper class]
                                     rootClass:[NsqRoot class]
                                          file:NsqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UserUpdateWrapper__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t UserUpdateWrapper_Action_RawValue(UserUpdateWrapper *message) {
  GPBDescriptor *descriptor = [UserUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UserUpdateWrapper_FieldNumber_Action];
  return GPBGetMessageInt32Field(message, field);
}

void SetUserUpdateWrapper_Action_RawValue(UserUpdateWrapper *message, int32_t value) {
  GPBDescriptor *descriptor = [UserUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:UserUpdateWrapper_FieldNumber_Action];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum UserUpdateWrapper_Action

GPBEnumDescriptor *UserUpdateWrapper_Action_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Create\000Update\000Delete\000";
    static const int32_t values[] = {
        UserUpdateWrapper_Action_Unknown,
        UserUpdateWrapper_Action_Create,
        UserUpdateWrapper_Action_Update,
        UserUpdateWrapper_Action_Delete,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(UserUpdateWrapper_Action)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:UserUpdateWrapper_Action_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL UserUpdateWrapper_Action_IsValidValue(int32_t value__) {
  switch (value__) {
    case UserUpdateWrapper_Action_Unknown:
    case UserUpdateWrapper_Action_Create:
    case UserUpdateWrapper_Action_Update:
    case UserUpdateWrapper_Action_Delete:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - HubMembershipUpdateWrapper

@implementation HubMembershipUpdateWrapper

@dynamic timestamp;
@dynamic action;
@dynamic userId;
@dynamic hubId;
@dynamic hasUser, user;
@dynamic hasHubMembership, hubMembership;
@dynamic hasHubGroupMembership, hubGroupMembership;

typedef struct HubMembershipUpdateWrapper__storage_ {
  uint32_t _has_storage_[1];
  HubMembershipUpdateWrapper_Action action;
  NSString *userId;
  NSString *hubId;
  User *user;
  HubMembershipRecord *hubMembership;
  GroupMembershipRecord *hubGroupMembership;
  int64_t timestamp;
} HubMembershipUpdateWrapper__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = HubMembershipUpdateWrapper_FieldNumber_Timestamp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(HubMembershipUpdateWrapper__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "action",
        .dataTypeSpecific.enumDescFunc = HubMembershipUpdateWrapper_Action_EnumDescriptor,
        .number = HubMembershipUpdateWrapper_FieldNumber_Action,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(HubMembershipUpdateWrapper__storage_, action),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = HubMembershipUpdateWrapper_FieldNumber_UserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(HubMembershipUpdateWrapper__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "hubId",
        .dataTypeSpecific.className = NULL,
        .number = HubMembershipUpdateWrapper_FieldNumber_HubId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(HubMembershipUpdateWrapper__storage_, hubId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(User),
        .number = HubMembershipUpdateWrapper_FieldNumber_User,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(HubMembershipUpdateWrapper__storage_, user),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "hubMembership",
        .dataTypeSpecific.className = GPBStringifySymbol(HubMembershipRecord),
        .number = HubMembershipUpdateWrapper_FieldNumber_HubMembership,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(HubMembershipUpdateWrapper__storage_, hubMembership),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "hubGroupMembership",
        .dataTypeSpecific.className = GPBStringifySymbol(GroupMembershipRecord),
        .number = HubMembershipUpdateWrapper_FieldNumber_HubGroupMembership,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(HubMembershipUpdateWrapper__storage_, hubGroupMembership),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[HubMembershipUpdateWrapper class]
                                     rootClass:[NsqRoot class]
                                          file:NsqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(HubMembershipUpdateWrapper__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t HubMembershipUpdateWrapper_Action_RawValue(HubMembershipUpdateWrapper *message) {
  GPBDescriptor *descriptor = [HubMembershipUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:HubMembershipUpdateWrapper_FieldNumber_Action];
  return GPBGetMessageInt32Field(message, field);
}

void SetHubMembershipUpdateWrapper_Action_RawValue(HubMembershipUpdateWrapper *message, int32_t value) {
  GPBDescriptor *descriptor = [HubMembershipUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:HubMembershipUpdateWrapper_FieldNumber_Action];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum HubMembershipUpdateWrapper_Action

GPBEnumDescriptor *HubMembershipUpdateWrapper_Action_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Create\000Update\000Delete\000";
    static const int32_t values[] = {
        HubMembershipUpdateWrapper_Action_Unknown,
        HubMembershipUpdateWrapper_Action_Create,
        HubMembershipUpdateWrapper_Action_Update,
        HubMembershipUpdateWrapper_Action_Delete,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(HubMembershipUpdateWrapper_Action)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:HubMembershipUpdateWrapper_Action_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL HubMembershipUpdateWrapper_Action_IsValidValue(int32_t value__) {
  switch (value__) {
    case HubMembershipUpdateWrapper_Action_Unknown:
    case HubMembershipUpdateWrapper_Action_Create:
    case HubMembershipUpdateWrapper_Action_Update:
    case HubMembershipUpdateWrapper_Action_Delete:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - ChannelMembershipUpdateWrapper

@implementation ChannelMembershipUpdateWrapper

@dynamic timestamp;
@dynamic action;
@dynamic userId;
@dynamic channelId;
@dynamic hasChannelMembership, channelMembership;

typedef struct ChannelMembershipUpdateWrapper__storage_ {
  uint32_t _has_storage_[1];
  ChannelMembershipUpdateWrapper_Action action;
  NSString *userId;
  NSString *channelId;
  ChannelMembershipRecord *channelMembership;
  int64_t timestamp;
} ChannelMembershipUpdateWrapper__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = ChannelMembershipUpdateWrapper_FieldNumber_Timestamp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ChannelMembershipUpdateWrapper__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "action",
        .dataTypeSpecific.enumDescFunc = ChannelMembershipUpdateWrapper_Action_EnumDescriptor,
        .number = ChannelMembershipUpdateWrapper_FieldNumber_Action,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ChannelMembershipUpdateWrapper__storage_, action),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = ChannelMembershipUpdateWrapper_FieldNumber_UserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ChannelMembershipUpdateWrapper__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "channelId",
        .dataTypeSpecific.className = NULL,
        .number = ChannelMembershipUpdateWrapper_FieldNumber_ChannelId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ChannelMembershipUpdateWrapper__storage_, channelId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "channelMembership",
        .dataTypeSpecific.className = GPBStringifySymbol(ChannelMembershipRecord),
        .number = ChannelMembershipUpdateWrapper_FieldNumber_ChannelMembership,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ChannelMembershipUpdateWrapper__storage_, channelMembership),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ChannelMembershipUpdateWrapper class]
                                     rootClass:[NsqRoot class]
                                          file:NsqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ChannelMembershipUpdateWrapper__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t ChannelMembershipUpdateWrapper_Action_RawValue(ChannelMembershipUpdateWrapper *message) {
  GPBDescriptor *descriptor = [ChannelMembershipUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ChannelMembershipUpdateWrapper_FieldNumber_Action];
  return GPBGetMessageInt32Field(message, field);
}

void SetChannelMembershipUpdateWrapper_Action_RawValue(ChannelMembershipUpdateWrapper *message, int32_t value) {
  GPBDescriptor *descriptor = [ChannelMembershipUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ChannelMembershipUpdateWrapper_FieldNumber_Action];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum ChannelMembershipUpdateWrapper_Action

GPBEnumDescriptor *ChannelMembershipUpdateWrapper_Action_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Create\000Update\000Delete\000";
    static const int32_t values[] = {
        ChannelMembershipUpdateWrapper_Action_Unknown,
        ChannelMembershipUpdateWrapper_Action_Create,
        ChannelMembershipUpdateWrapper_Action_Update,
        ChannelMembershipUpdateWrapper_Action_Delete,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(ChannelMembershipUpdateWrapper_Action)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:ChannelMembershipUpdateWrapper_Action_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL ChannelMembershipUpdateWrapper_Action_IsValidValue(int32_t value__) {
  switch (value__) {
    case ChannelMembershipUpdateWrapper_Action_Unknown:
    case ChannelMembershipUpdateWrapper_Action_Create:
    case ChannelMembershipUpdateWrapper_Action_Update:
    case ChannelMembershipUpdateWrapper_Action_Delete:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - GroupMembershipUpdateWrapper

@implementation GroupMembershipUpdateWrapper

@dynamic timestamp;
@dynamic action;
@dynamic userId;
@dynamic groupId;
@dynamic hasGroupMembership, groupMembership;
@dynamic linkedHubIdsArray, linkedHubIdsArray_Count;

typedef struct GroupMembershipUpdateWrapper__storage_ {
  uint32_t _has_storage_[1];
  GroupMembershipUpdateWrapper_Action action;
  NSString *userId;
  NSString *groupId;
  GroupMembershipRecord *groupMembership;
  NSMutableArray *linkedHubIdsArray;
  int64_t timestamp;
} GroupMembershipUpdateWrapper__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = GroupMembershipUpdateWrapper_FieldNumber_Timestamp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GroupMembershipUpdateWrapper__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "action",
        .dataTypeSpecific.enumDescFunc = GroupMembershipUpdateWrapper_Action_EnumDescriptor,
        .number = GroupMembershipUpdateWrapper_FieldNumber_Action,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GroupMembershipUpdateWrapper__storage_, action),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = GroupMembershipUpdateWrapper_FieldNumber_UserId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GroupMembershipUpdateWrapper__storage_, userId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupId",
        .dataTypeSpecific.className = NULL,
        .number = GroupMembershipUpdateWrapper_FieldNumber_GroupId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GroupMembershipUpdateWrapper__storage_, groupId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupMembership",
        .dataTypeSpecific.className = GPBStringifySymbol(GroupMembershipRecord),
        .number = GroupMembershipUpdateWrapper_FieldNumber_GroupMembership,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GroupMembershipUpdateWrapper__storage_, groupMembership),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "linkedHubIdsArray",
        .dataTypeSpecific.className = NULL,
        .number = GroupMembershipUpdateWrapper_FieldNumber_LinkedHubIdsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GroupMembershipUpdateWrapper__storage_, linkedHubIdsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GroupMembershipUpdateWrapper class]
                                     rootClass:[NsqRoot class]
                                          file:NsqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GroupMembershipUpdateWrapper__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GroupMembershipUpdateWrapper_Action_RawValue(GroupMembershipUpdateWrapper *message) {
  GPBDescriptor *descriptor = [GroupMembershipUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GroupMembershipUpdateWrapper_FieldNumber_Action];
  return GPBGetMessageInt32Field(message, field);
}

void SetGroupMembershipUpdateWrapper_Action_RawValue(GroupMembershipUpdateWrapper *message, int32_t value) {
  GPBDescriptor *descriptor = [GroupMembershipUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GroupMembershipUpdateWrapper_FieldNumber_Action];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum GroupMembershipUpdateWrapper_Action

GPBEnumDescriptor *GroupMembershipUpdateWrapper_Action_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Create\000Update\000Delete\000";
    static const int32_t values[] = {
        GroupMembershipUpdateWrapper_Action_Unknown,
        GroupMembershipUpdateWrapper_Action_Create,
        GroupMembershipUpdateWrapper_Action_Update,
        GroupMembershipUpdateWrapper_Action_Delete,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GroupMembershipUpdateWrapper_Action)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GroupMembershipUpdateWrapper_Action_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GroupMembershipUpdateWrapper_Action_IsValidValue(int32_t value__) {
  switch (value__) {
    case GroupMembershipUpdateWrapper_Action_Unknown:
    case GroupMembershipUpdateWrapper_Action_Create:
    case GroupMembershipUpdateWrapper_Action_Update:
    case GroupMembershipUpdateWrapper_Action_Delete:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - HubLinkUpdateWrapper

@implementation HubLinkUpdateWrapper

@dynamic timestamp;
@dynamic action;
@dynamic hubId;
@dynamic groupId;

typedef struct HubLinkUpdateWrapper__storage_ {
  uint32_t _has_storage_[1];
  HubLinkUpdateWrapper_Action action;
  NSString *hubId;
  NSString *groupId;
  int64_t timestamp;
} HubLinkUpdateWrapper__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = HubLinkUpdateWrapper_FieldNumber_Timestamp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(HubLinkUpdateWrapper__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "action",
        .dataTypeSpecific.enumDescFunc = HubLinkUpdateWrapper_Action_EnumDescriptor,
        .number = HubLinkUpdateWrapper_FieldNumber_Action,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(HubLinkUpdateWrapper__storage_, action),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "hubId",
        .dataTypeSpecific.className = NULL,
        .number = HubLinkUpdateWrapper_FieldNumber_HubId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(HubLinkUpdateWrapper__storage_, hubId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupId",
        .dataTypeSpecific.className = NULL,
        .number = HubLinkUpdateWrapper_FieldNumber_GroupId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(HubLinkUpdateWrapper__storage_, groupId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[HubLinkUpdateWrapper class]
                                     rootClass:[NsqRoot class]
                                          file:NsqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(HubLinkUpdateWrapper__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t HubLinkUpdateWrapper_Action_RawValue(HubLinkUpdateWrapper *message) {
  GPBDescriptor *descriptor = [HubLinkUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:HubLinkUpdateWrapper_FieldNumber_Action];
  return GPBGetMessageInt32Field(message, field);
}

void SetHubLinkUpdateWrapper_Action_RawValue(HubLinkUpdateWrapper *message, int32_t value) {
  GPBDescriptor *descriptor = [HubLinkUpdateWrapper descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:HubLinkUpdateWrapper_FieldNumber_Action];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum HubLinkUpdateWrapper_Action

GPBEnumDescriptor *HubLinkUpdateWrapper_Action_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Link\000Unlink\000";
    static const int32_t values[] = {
        HubLinkUpdateWrapper_Action_Unknown,
        HubLinkUpdateWrapper_Action_Link,
        HubLinkUpdateWrapper_Action_Unlink,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(HubLinkUpdateWrapper_Action)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:HubLinkUpdateWrapper_Action_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL HubLinkUpdateWrapper_Action_IsValidValue(int32_t value__) {
  switch (value__) {
    case HubLinkUpdateWrapper_Action_Unknown:
    case HubLinkUpdateWrapper_Action_Link:
    case HubLinkUpdateWrapper_Action_Unlink:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - UserCountsUpdatedEvent

@implementation UserCountsUpdatedEvent

@dynamic communityIdsArray, communityIdsArray_Count;

typedef struct UserCountsUpdatedEvent__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *communityIdsArray;
} UserCountsUpdatedEvent__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "communityIdsArray",
        .dataTypeSpecific.className = NULL,
        .number = UserCountsUpdatedEvent_FieldNumber_CommunityIdsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(UserCountsUpdatedEvent__storage_, communityIdsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UserCountsUpdatedEvent class]
                                     rootClass:[NsqRoot class]
                                          file:NsqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UserCountsUpdatedEvent__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
