// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Any;
@class Hub;
@class SearchGame;
@class SearchGroup;
@class SearchUser;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SearchHit_Type

typedef GPB_ENUM(SearchHit_Type) {
  SearchHit_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  SearchHit_Type_Unknown = 0,
  SearchHit_Type_Group = 1,
  SearchHit_Type_User = 2,
  SearchHit_Type_Game = 3,
  SearchHit_Type_Community = 4,
};

GPBEnumDescriptor *SearchHit_Type_EnumDescriptor(void);

BOOL SearchHit_Type_IsValidValue(int32_t value);

#pragma mark - Enum Suggestion_Type

typedef GPB_ENUM(Suggestion_Type) {
  Suggestion_Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Suggestion_Type_Unknown = 0,
  Suggestion_Type_Group = 1,
  Suggestion_Type_User = 2,
  Suggestion_Type_Game = 3,
  Suggestion_Type_Community = 4,
};

GPBEnumDescriptor *Suggestion_Type_EnumDescriptor(void);

BOOL Suggestion_Type_IsValidValue(int32_t value);

#pragma mark - SearchRoot

@interface SearchRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - SearchRequest

typedef GPB_ENUM(SearchRequest_FieldNumber) {
  SearchRequest_FieldNumber_TypesArray = 1,
  SearchRequest_FieldNumber_FieldsArray = 2,
  SearchRequest_FieldNumber_Text = 3,
  SearchRequest_FieldNumber_Fuzzy = 4,
  SearchRequest_FieldNumber_Size = 5,
  SearchRequest_FieldNumber_From = 6,
};

@interface SearchRequest : GPBMessage

// |typesArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *typesArray;
@property(nonatomic, readonly) NSUInteger typesArray_Count;

// |fieldsArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *fieldsArray;
@property(nonatomic, readonly) NSUInteger fieldsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@property(nonatomic, readwrite) BOOL fuzzy;

@property(nonatomic, readwrite) int32_t size;

@property(nonatomic, readwrite) int32_t from;

@end

#pragma mark - SearchResponse

typedef GPB_ENUM(SearchResponse_FieldNumber) {
  SearchResponse_FieldNumber_Hits = 1,
  SearchResponse_FieldNumber_From = 2,
};

@interface SearchResponse : GPBMessage

// |hits| values are |SearchHits|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary *hits;
@property(nonatomic, readonly) NSUInteger hits_Count;

@property(nonatomic, readwrite) int32_t from;

@end

#pragma mark - SearchHits

typedef GPB_ENUM(SearchHits_FieldNumber) {
  SearchHits_FieldNumber_HitsArray = 1,
  SearchHits_FieldNumber_Type = 2,
  SearchHits_FieldNumber_Total = 3,
};

@interface SearchHits : GPBMessage

// |hitsArray| contains |SearchHit|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *hitsArray;
@property(nonatomic, readonly) NSUInteger hitsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite) int64_t total;

@end

#pragma mark - SearchHit

typedef GPB_ENUM(SearchHit_FieldNumber) {
  SearchHit_FieldNumber_Score = 1,
  SearchHit_FieldNumber_Index = 2,
  SearchHit_FieldNumber_Type = 3,
  SearchHit_FieldNumber_Id_p = 4,
  SearchHit_FieldNumber_Highlights = 5,
  SearchHit_FieldNumber_User = 10,
  SearchHit_FieldNumber_Group = 11,
  SearchHit_FieldNumber_Game = 12,
  SearchHit_FieldNumber_Community = 13,
};

typedef GPB_ENUM(SearchHit_Source_OneOfCase) {
  SearchHit_Source_OneOfCase_GPBUnsetOneOfCase = 0,
  SearchHit_Source_OneOfCase_User = 10,
  SearchHit_Source_OneOfCase_Group = 11,
  SearchHit_Source_OneOfCase_Game = 12,
  SearchHit_Source_OneOfCase_Community = 13,
};

@interface SearchHit : GPBMessage

@property(nonatomic, readwrite) float score;

@property(nonatomic, readwrite, copy, null_resettable) NSString *index;

@property(nonatomic, readwrite) SearchHit_Type type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

// |highlights| values are |Highlights|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary *highlights;
@property(nonatomic, readonly) NSUInteger highlights_Count;

@property(nonatomic, readonly) SearchHit_Source_OneOfCase sourceOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) SearchUser *user;

@property(nonatomic, readwrite, strong, null_resettable) SearchGroup *group;

@property(nonatomic, readwrite, strong, null_resettable) SearchGame *game;

@property(nonatomic, readwrite, strong, null_resettable) Hub *community;

@end

int32_t SearchHit_Type_RawValue(SearchHit *message);
void SetSearchHit_Type_RawValue(SearchHit *message, int32_t value);

void SearchHit_ClearSourceOneOfCase(SearchHit *message);

#pragma mark - Highlights

typedef GPB_ENUM(Highlights_FieldNumber) {
  Highlights_FieldNumber_Field = 1,
  Highlights_FieldNumber_HighlightsArray = 2,
};

@interface Highlights : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *field;

// |highlightsArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *highlightsArray;
@property(nonatomic, readonly) NSUInteger highlightsArray_Count;

@end

#pragma mark - IndexResponse

typedef GPB_ENUM(IndexResponse_FieldNumber) {
  IndexResponse_FieldNumber_Index = 1,
  IndexResponse_FieldNumber_Type = 2,
  IndexResponse_FieldNumber_Id_p = 3,
  IndexResponse_FieldNumber_Version = 4,
  IndexResponse_FieldNumber_Created = 5,
};

@interface IndexResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *index;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t version;

@property(nonatomic, readwrite) BOOL created;

@end

#pragma mark - DeleteResponse

typedef GPB_ENUM(DeleteResponse_FieldNumber) {
  DeleteResponse_FieldNumber_Found = 1,
  DeleteResponse_FieldNumber_Index = 2,
  DeleteResponse_FieldNumber_Type = 3,
  DeleteResponse_FieldNumber_Id_p = 4,
  DeleteResponse_FieldNumber_Version = 5,
};

@interface DeleteResponse : GPBMessage

@property(nonatomic, readwrite) BOOL found;

@property(nonatomic, readwrite, copy, null_resettable) NSString *index;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) int64_t version;

@end

#pragma mark - Suggestion

typedef GPB_ENUM(Suggestion_FieldNumber) {
  Suggestion_FieldNumber_Id_p = 1,
  Suggestion_FieldNumber_Type = 2,
  Suggestion_FieldNumber_Title = 3,
  Suggestion_FieldNumber_Image = 4,
  Suggestion_FieldNumber_DeprecatedProprietary = 5,
  Suggestion_FieldNumber_Data_p = 6,
};

@interface Suggestion : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) Suggestion_Type type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *image;

@property(nonatomic, readwrite, copy, null_resettable) NSData *deprecatedProprietary;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Any *data_p;

@end

int32_t Suggestion_Type_RawValue(Suggestion *message);
void SetSuggestion_Type_RawValue(Suggestion *message, int32_t value);

#pragma mark - SuggestionRequest

typedef GPB_ENUM(SuggestionRequest_FieldNumber) {
  SuggestionRequest_FieldNumber_Text = 1,
  SuggestionRequest_FieldNumber_Fuzzy = 2,
  SuggestionRequest_FieldNumber_ContextArray = 3,
};

@interface SuggestionRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@property(nonatomic, readwrite) BOOL fuzzy;

// |contextArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *contextArray;
@property(nonatomic, readonly) NSUInteger contextArray_Count;

@end

#pragma mark - SuggestionResponse

typedef GPB_ENUM(SuggestionResponse_FieldNumber) {
  SuggestionResponse_FieldNumber_SuggestionsArray = 1,
};

@interface SuggestionResponse : GPBMessage

// |suggestionsArray| contains |Suggestion|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *suggestionsArray;
@property(nonatomic, readonly) NSUInteger suggestionsArray_Count;

@end

#pragma mark - SearchGroup

typedef GPB_ENUM(SearchGroup_FieldNumber) {
  SearchGroup_FieldNumber_Id_p = 1,
  SearchGroup_FieldNumber_Name = 2,
  SearchGroup_FieldNumber_Description_p = 3,
  SearchGroup_FieldNumber_TitleImage = 4,
  SearchGroup_FieldNumber_BackgroundImage = 5,
  SearchGroup_FieldNumber_ChannelsArray = 6,
};

@interface SearchGroup : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *titleImage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *backgroundImage;

// |channelsArray| contains |SearchChannel|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *channelsArray;
@property(nonatomic, readonly) NSUInteger channelsArray_Count;

@end

#pragma mark - SearchGame

typedef GPB_ENUM(SearchGame_FieldNumber) {
  SearchGame_FieldNumber_Id_p = 1,
  SearchGame_FieldNumber_Name = 2,
  SearchGame_FieldNumber_ShortName = 3,
  SearchGame_FieldNumber_TitleImage = 4,
  SearchGame_FieldNumber_BackgroundImagesArray = 5,
  SearchGame_FieldNumber_ChannelsArray = 6,
};

@interface SearchGame : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *shortName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *titleImage;

// |backgroundImagesArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *backgroundImagesArray;
@property(nonatomic, readonly) NSUInteger backgroundImagesArray_Count;

// |channelsArray| contains |SearchChannel|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *channelsArray;
@property(nonatomic, readonly) NSUInteger channelsArray_Count;

@end

#pragma mark - SearchChannel

typedef GPB_ENUM(SearchChannel_FieldNumber) {
  SearchChannel_FieldNumber_Id_p = 1,
  SearchChannel_FieldNumber_Title = 2,
  SearchChannel_FieldNumber_Topic = 3,
  SearchChannel_FieldNumber_TagsArray = 4,
};

@interface SearchChannel : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *topic;

// |tagsArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *tagsArray;
@property(nonatomic, readonly) NSUInteger tagsArray_Count;

@end

#pragma mark - SearchUser

typedef GPB_ENUM(SearchUser_FieldNumber) {
  SearchUser_FieldNumber_Id_p = 1,
  SearchUser_FieldNumber_Name = 2,
  SearchUser_FieldNumber_AvatarImage = 3,
  SearchUser_FieldNumber_BackgroundImage = 4,
};

@interface SearchUser : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarImage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *backgroundImage;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
