// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sip.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(ChannelMembershipRecord_VoiceStatus);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SipRoot

@interface SipRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - SipGetDeviceResponse

typedef GPB_ENUM(SipGetDeviceResponse_FieldNumber) {
  SipGetDeviceResponse_FieldNumber_PrivateId = 1,
  SipGetDeviceResponse_FieldNumber_PublicId = 2,
  SipGetDeviceResponse_FieldNumber_Realm = 3,
  SipGetDeviceResponse_FieldNumber_Password = 4,
};

@interface SipGetDeviceResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *privateId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *publicId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *realm;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@end

#pragma mark - SipGetConferenceResponse

typedef GPB_ENUM(SipGetConferenceResponse_FieldNumber) {
  SipGetConferenceResponse_FieldNumber_Address = 1,
};

@interface SipGetConferenceResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@end

#pragma mark - SipSetConferenceStatusRequest

typedef GPB_ENUM(SipSetConferenceStatusRequest_FieldNumber) {
  SipSetConferenceStatusRequest_FieldNumber_VoiceStatus = 1,
};

@interface SipSetConferenceStatusRequest : GPBMessage

@property(nonatomic, readwrite) enum ChannelMembershipRecord_VoiceStatus voiceStatus;

@end

int32_t SipSetConferenceStatusRequest_VoiceStatus_RawValue(SipSetConferenceStatusRequest *message);
void SetSipSetConferenceStatusRequest_VoiceStatus_RawValue(SipSetConferenceStatusRequest *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
