// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userlist.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "Userlist.pbobjc.h"
#import "Any.pbobjc.h"
#import "Profile.pbobjc.h"
#import "HubBase.pbobjc.h"
#import "Hub.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - UserlistRoot

@implementation UserlistRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[AnyRoot extensionRegistry]];
    [registry addExtensions:[ProfileRoot extensionRegistry]];
    [registry addExtensions:[HubBaseRoot extensionRegistry]];
    [registry addExtensions:[HubRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - UserlistRoot_FileDescriptor

static GPBFileDescriptor *UserlistRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"proto"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - RPCUserlistGetChannelUsersRequest

@implementation RPCUserlistGetChannelUsersRequest

@dynamic requestingUserId;
@dynamic channelId;
@dynamic size;
@dynamic from;
@dynamic excludeOffline;

typedef struct RPCUserlistGetChannelUsersRequest__storage_ {
  uint32_t _has_storage_[1];
  BOOL excludeOffline;
  NSString *requestingUserId;
  NSString *channelId;
  int64_t size;
  int64_t from;
} RPCUserlistGetChannelUsersRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "requestingUserId",
        .number = RPCUserlistGetChannelUsersRequest_FieldNumber_RequestingUserId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RPCUserlistGetChannelUsersRequest__storage_, requestingUserId),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "channelId",
        .number = RPCUserlistGetChannelUsersRequest_FieldNumber_ChannelId,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RPCUserlistGetChannelUsersRequest__storage_, channelId),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "size",
        .number = RPCUserlistGetChannelUsersRequest_FieldNumber_Size,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetChannelUsersRequest__storage_, size),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "from",
        .number = RPCUserlistGetChannelUsersRequest_FieldNumber_From,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetChannelUsersRequest__storage_, from),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "excludeOffline",
        .number = RPCUserlistGetChannelUsersRequest_FieldNumber_ExcludeOffline,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
        .offset = offsetof(RPCUserlistGetChannelUsersRequest__storage_, excludeOffline),
        .defaultValue.valueBool = NO,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RPCUserlistGetChannelUsersRequest class]
                                     rootClass:[UserlistRoot class]
                                          file:UserlistRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RPCUserlistGetChannelUsersRequest__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RPCUserlistGetChannelUsersResponse

@implementation RPCUserlistGetChannelUsersResponse

@dynamic error;
@dynamic totalUsers;
@dynamic from;
@dynamic usersArray, usersArray_Count;
@dynamic onlineUsers;
@dynamic pagedUsers;

typedef struct RPCUserlistGetChannelUsersResponse__storage_ {
  uint32_t _has_storage_[1];
  RPCUserlistGetChannelUsersResponse_ErrorType error;
  NSMutableArray *usersArray;
  int64_t totalUsers;
  int64_t from;
  int64_t onlineUsers;
  int64_t pagedUsers;
} RPCUserlistGetChannelUsersResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "error",
        .number = RPCUserlistGetChannelUsersResponse_FieldNumber_Error,
        .hasIndex = 0,
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
        .offset = offsetof(RPCUserlistGetChannelUsersResponse__storage_, error),
        .defaultValue.valueEnum = RPCUserlistGetChannelUsersResponse_ErrorType_None,
        .dataTypeSpecific.enumDescFunc = RPCUserlistGetChannelUsersResponse_ErrorType_EnumDescriptor,
        .fieldOptions = NULL,
      },
      {
        .name = "totalUsers",
        .number = RPCUserlistGetChannelUsersResponse_FieldNumber_TotalUsers,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetChannelUsersResponse__storage_, totalUsers),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "from",
        .number = RPCUserlistGetChannelUsersResponse_FieldNumber_From,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetChannelUsersResponse__storage_, from),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "usersArray",
        .number = RPCUserlistGetChannelUsersResponse_FieldNumber_UsersArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(RPCUserlistGetChannelUsersResponse__storage_, usersArray),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(ChannelUser),
        .fieldOptions = NULL,
      },
      {
        .name = "onlineUsers",
        .number = RPCUserlistGetChannelUsersResponse_FieldNumber_OnlineUsers,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetChannelUsersResponse__storage_, onlineUsers),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "pagedUsers",
        .number = RPCUserlistGetChannelUsersResponse_FieldNumber_PagedUsers,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetChannelUsersResponse__storage_, pagedUsers),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    static GPBMessageEnumDescription enums[] = {
      { .enumDescriptorFunc = RPCUserlistGetChannelUsersResponse_ErrorType_EnumDescriptor },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RPCUserlistGetChannelUsersResponse class]
                                     rootClass:[UserlistRoot class]
                                          file:UserlistRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:enums
                                     enumCount:sizeof(enums) / sizeof(GPBMessageEnumDescription)
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RPCUserlistGetChannelUsersResponse__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t RPCUserlistGetChannelUsersResponse_Error_RawValue(RPCUserlistGetChannelUsersResponse *message) {
  GPBDescriptor *descriptor = [RPCUserlistGetChannelUsersResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RPCUserlistGetChannelUsersResponse_FieldNumber_Error];
  return GPBGetMessageInt32Field(message, field);
}

void SetRPCUserlistGetChannelUsersResponse_Error_RawValue(RPCUserlistGetChannelUsersResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [RPCUserlistGetChannelUsersResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RPCUserlistGetChannelUsersResponse_FieldNumber_Error];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum RPCUserlistGetChannelUsersResponse_ErrorType

GPBEnumDescriptor *RPCUserlistGetChannelUsersResponse_ErrorType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageEnumValueDescription values[] = {
      { .name = "None", .number = RPCUserlistGetChannelUsersResponse_ErrorType_None },
      { .name = "UnknownError", .number = RPCUserlistGetChannelUsersResponse_ErrorType_UnknownError },
      { .name = "BadRequest", .number = RPCUserlistGetChannelUsersResponse_ErrorType_BadRequest },
      { .name = "Forbidden", .number = RPCUserlistGetChannelUsersResponse_ErrorType_Forbidden },
    };
    descriptor = [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(RPCUserlistGetChannelUsersResponse_ErrorType)
                                                   values:values
                                               valueCount:sizeof(values) / sizeof(GPBMessageEnumValueDescription)
                                             enumVerifier:RPCUserlistGetChannelUsersResponse_ErrorType_IsValidValue];
  }
  return descriptor;
}

BOOL RPCUserlistGetChannelUsersResponse_ErrorType_IsValidValue(int32_t value__) {
  switch (value__) {
    case RPCUserlistGetChannelUsersResponse_ErrorType_None:
    case RPCUserlistGetChannelUsersResponse_ErrorType_UnknownError:
    case RPCUserlistGetChannelUsersResponse_ErrorType_BadRequest:
    case RPCUserlistGetChannelUsersResponse_ErrorType_Forbidden:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - RPCUserlistGetHubMembersRequest

@implementation RPCUserlistGetHubMembersRequest

@dynamic requestingUserId;
@dynamic hubId;
@dynamic size;
@dynamic from;

typedef struct RPCUserlistGetHubMembersRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *requestingUserId;
  NSString *hubId;
  int64_t size;
  int64_t from;
} RPCUserlistGetHubMembersRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "requestingUserId",
        .number = RPCUserlistGetHubMembersRequest_FieldNumber_RequestingUserId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RPCUserlistGetHubMembersRequest__storage_, requestingUserId),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "hubId",
        .number = RPCUserlistGetHubMembersRequest_FieldNumber_HubId,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RPCUserlistGetHubMembersRequest__storage_, hubId),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "size",
        .number = RPCUserlistGetHubMembersRequest_FieldNumber_Size,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetHubMembersRequest__storage_, size),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "from",
        .number = RPCUserlistGetHubMembersRequest_FieldNumber_From,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetHubMembersRequest__storage_, from),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RPCUserlistGetHubMembersRequest class]
                                     rootClass:[UserlistRoot class]
                                          file:UserlistRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RPCUserlistGetHubMembersRequest__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RPCUserlistGetHubMembersResponse

@implementation RPCUserlistGetHubMembersResponse

@dynamic error;
@dynamic totalUsers;
@dynamic from;
@dynamic usersArray, usersArray_Count;
@dynamic pagedUsers;

typedef struct RPCUserlistGetHubMembersResponse__storage_ {
  uint32_t _has_storage_[1];
  RPCUserlistGetHubMembersResponse_ErrorType error;
  NSMutableArray *usersArray;
  int64_t totalUsers;
  int64_t from;
  int64_t pagedUsers;
} RPCUserlistGetHubMembersResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "error",
        .number = RPCUserlistGetHubMembersResponse_FieldNumber_Error,
        .hasIndex = 0,
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
        .offset = offsetof(RPCUserlistGetHubMembersResponse__storage_, error),
        .defaultValue.valueEnum = RPCUserlistGetHubMembersResponse_ErrorType_None,
        .dataTypeSpecific.enumDescFunc = RPCUserlistGetHubMembersResponse_ErrorType_EnumDescriptor,
        .fieldOptions = NULL,
      },
      {
        .name = "totalUsers",
        .number = RPCUserlistGetHubMembersResponse_FieldNumber_TotalUsers,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetHubMembersResponse__storage_, totalUsers),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "from",
        .number = RPCUserlistGetHubMembersResponse_FieldNumber_From,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetHubMembersResponse__storage_, from),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "usersArray",
        .number = RPCUserlistGetHubMembersResponse_FieldNumber_UsersArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(RPCUserlistGetHubMembersResponse__storage_, usersArray),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(MembershipEntry),
        .fieldOptions = NULL,
      },
      {
        .name = "pagedUsers",
        .number = RPCUserlistGetHubMembersResponse_FieldNumber_PagedUsers,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetHubMembersResponse__storage_, pagedUsers),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    static GPBMessageEnumDescription enums[] = {
      { .enumDescriptorFunc = RPCUserlistGetHubMembersResponse_ErrorType_EnumDescriptor },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RPCUserlistGetHubMembersResponse class]
                                     rootClass:[UserlistRoot class]
                                          file:UserlistRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:enums
                                     enumCount:sizeof(enums) / sizeof(GPBMessageEnumDescription)
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RPCUserlistGetHubMembersResponse__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t RPCUserlistGetHubMembersResponse_Error_RawValue(RPCUserlistGetHubMembersResponse *message) {
  GPBDescriptor *descriptor = [RPCUserlistGetHubMembersResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RPCUserlistGetHubMembersResponse_FieldNumber_Error];
  return GPBGetMessageInt32Field(message, field);
}

void SetRPCUserlistGetHubMembersResponse_Error_RawValue(RPCUserlistGetHubMembersResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [RPCUserlistGetHubMembersResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RPCUserlistGetHubMembersResponse_FieldNumber_Error];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum RPCUserlistGetHubMembersResponse_ErrorType

GPBEnumDescriptor *RPCUserlistGetHubMembersResponse_ErrorType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageEnumValueDescription values[] = {
      { .name = "None", .number = RPCUserlistGetHubMembersResponse_ErrorType_None },
      { .name = "UnknownError", .number = RPCUserlistGetHubMembersResponse_ErrorType_UnknownError },
      { .name = "BadRequest", .number = RPCUserlistGetHubMembersResponse_ErrorType_BadRequest },
      { .name = "Forbidden", .number = RPCUserlistGetHubMembersResponse_ErrorType_Forbidden },
    };
    descriptor = [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(RPCUserlistGetHubMembersResponse_ErrorType)
                                                   values:values
                                               valueCount:sizeof(values) / sizeof(GPBMessageEnumValueDescription)
                                             enumVerifier:RPCUserlistGetHubMembersResponse_ErrorType_IsValidValue];
  }
  return descriptor;
}

BOOL RPCUserlistGetHubMembersResponse_ErrorType_IsValidValue(int32_t value__) {
  switch (value__) {
    case RPCUserlistGetHubMembersResponse_ErrorType_None:
    case RPCUserlistGetHubMembersResponse_ErrorType_UnknownError:
    case RPCUserlistGetHubMembersResponse_ErrorType_BadRequest:
    case RPCUserlistGetHubMembersResponse_ErrorType_Forbidden:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - RPCUserlistSearchHubMembersRequest

@implementation RPCUserlistSearchHubMembersRequest

@dynamic requestingUserId;
@dynamic hubId;
@dynamic size;
@dynamic from;
@dynamic term;
@dynamic fuzzy;

typedef struct RPCUserlistSearchHubMembersRequest__storage_ {
  uint32_t _has_storage_[1];
  BOOL fuzzy;
  NSString *requestingUserId;
  NSString *hubId;
  NSString *term;
  int64_t size;
  int64_t from;
} RPCUserlistSearchHubMembersRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "requestingUserId",
        .number = RPCUserlistSearchHubMembersRequest_FieldNumber_RequestingUserId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RPCUserlistSearchHubMembersRequest__storage_, requestingUserId),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "hubId",
        .number = RPCUserlistSearchHubMembersRequest_FieldNumber_HubId,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RPCUserlistSearchHubMembersRequest__storage_, hubId),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "size",
        .number = RPCUserlistSearchHubMembersRequest_FieldNumber_Size,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistSearchHubMembersRequest__storage_, size),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "from",
        .number = RPCUserlistSearchHubMembersRequest_FieldNumber_From,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistSearchHubMembersRequest__storage_, from),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "term",
        .number = RPCUserlistSearchHubMembersRequest_FieldNumber_Term,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RPCUserlistSearchHubMembersRequest__storage_, term),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "fuzzy",
        .number = RPCUserlistSearchHubMembersRequest_FieldNumber_Fuzzy,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
        .offset = offsetof(RPCUserlistSearchHubMembersRequest__storage_, fuzzy),
        .defaultValue.valueBool = NO,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RPCUserlistSearchHubMembersRequest class]
                                     rootClass:[UserlistRoot class]
                                          file:UserlistRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RPCUserlistSearchHubMembersRequest__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RPCUserlistSearchHubMembersResponse

@implementation RPCUserlistSearchHubMembersResponse

@dynamic error;
@dynamic from;
@dynamic usersArray, usersArray_Count;
@dynamic pagedUsers;

typedef struct RPCUserlistSearchHubMembersResponse__storage_ {
  uint32_t _has_storage_[1];
  SearchMembersResponse_ErrorType error;
  NSMutableArray *usersArray;
  int64_t from;
  int64_t pagedUsers;
} RPCUserlistSearchHubMembersResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "error",
        .number = RPCUserlistSearchHubMembersResponse_FieldNumber_Error,
        .hasIndex = 0,
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
        .offset = offsetof(RPCUserlistSearchHubMembersResponse__storage_, error),
        .defaultValue.valueEnum = SearchMembersResponse_ErrorType_None,
        .dataTypeSpecific.enumDescFunc = SearchMembersResponse_ErrorType_EnumDescriptor,
        .fieldOptions = NULL,
      },
      {
        .name = "from",
        .number = RPCUserlistSearchHubMembersResponse_FieldNumber_From,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistSearchHubMembersResponse__storage_, from),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "usersArray",
        .number = RPCUserlistSearchHubMembersResponse_FieldNumber_UsersArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
        .offset = offsetof(RPCUserlistSearchHubMembersResponse__storage_, usersArray),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = GPBStringifySymbol(MembershipEntry),
        .fieldOptions = NULL,
      },
      {
        .name = "pagedUsers",
        .number = RPCUserlistSearchHubMembersResponse_FieldNumber_PagedUsers,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistSearchHubMembersResponse__storage_, pagedUsers),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RPCUserlistSearchHubMembersResponse class]
                                     rootClass:[UserlistRoot class]
                                          file:UserlistRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RPCUserlistSearchHubMembersResponse__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t RPCUserlistSearchHubMembersResponse_Error_RawValue(RPCUserlistSearchHubMembersResponse *message) {
  GPBDescriptor *descriptor = [RPCUserlistSearchHubMembersResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RPCUserlistSearchHubMembersResponse_FieldNumber_Error];
  return GPBGetMessageInt32Field(message, field);
}

void SetRPCUserlistSearchHubMembersResponse_Error_RawValue(RPCUserlistSearchHubMembersResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [RPCUserlistSearchHubMembersResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:RPCUserlistSearchHubMembersResponse_FieldNumber_Error];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - RPCUserlistGetUserCountsRequest

@implementation RPCUserlistGetUserCountsRequest

@dynamic requestingUserId;
@dynamic hubIdsArray, hubIdsArray_Count;
@dynamic excludeOffline;

typedef struct RPCUserlistGetUserCountsRequest__storage_ {
  uint32_t _has_storage_[1];
  BOOL excludeOffline;
  NSString *requestingUserId;
  NSMutableArray *hubIdsArray;
} RPCUserlistGetUserCountsRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "requestingUserId",
        .number = RPCUserlistGetUserCountsRequest_FieldNumber_RequestingUserId,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RPCUserlistGetUserCountsRequest__storage_, requestingUserId),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "hubIdsArray",
        .number = RPCUserlistGetUserCountsRequest_FieldNumber_HubIdsArray,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
        .offset = offsetof(RPCUserlistGetUserCountsRequest__storage_, hubIdsArray),
        .defaultValue.valueMessage = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "excludeOffline",
        .number = RPCUserlistGetUserCountsRequest_FieldNumber_ExcludeOffline,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
        .offset = offsetof(RPCUserlistGetUserCountsRequest__storage_, excludeOffline),
        .defaultValue.valueBool = NO,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RPCUserlistGetUserCountsRequest class]
                                     rootClass:[UserlistRoot class]
                                          file:UserlistRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RPCUserlistGetUserCountsRequest__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RPCUserlistGetUserCountsResponse

@implementation RPCUserlistGetUserCountsResponse

@dynamic counts, counts_Count;

typedef struct RPCUserlistGetUserCountsResponse__storage_ {
  uint32_t _has_storage_[1];
  GPBStringInt64Dictionary *counts;
} RPCUserlistGetUserCountsResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "counts",
        .number = RPCUserlistGetUserCountsResponse_FieldNumber_Counts,
        .hasIndex = GPBNoHasBit,
        .flags = GPBFieldMapKeyString,
        .dataType = GPBDataTypeInt64,
        .offset = offsetof(RPCUserlistGetUserCountsResponse__storage_, counts),
        .defaultValue.valueInt64 = 0LL,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RPCUserlistGetUserCountsResponse class]
                                     rootClass:[UserlistRoot class]
                                          file:UserlistRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(RPCUserlistGetUserCountsResponse__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
